### ISSUE TITLE
setup.py/install_requires vs requirements.txt

### ISSUE THREAD

**Issue by qwcode** [pypa/packaging.python.org#10]
3 distinctions to cover I think:
- abstract vs concrete requirements (https://caremad.io/blog/setup-vs-requirement/)
- minimally defined vs exhaustive or frozen (http://stackoverflow.com/a/7085000)
- project requirements vs environment requirements.

**Comment by hickford** [comment]
Cool thanks for explaining. I think the guide should be strengthened to be more prescriptive:

1. Always use setup.py `install_requires`
2. You are free to write `requirements.txt` if you like
