### ISSUE TITLE
setup.cfg in https://packaging.python.org/tutorials/packaging-projects/ does not work

### ISSUE THREAD

**Issue by richtong** [pypa/packaging.python.org#1001]
Even if you copy and paste the setup.cfg directly from the site, the src directory is not picked up. The setup.py works fine. Is there some hidden syntax here that a noob needs to know I see the use of four spaces is that significant? in package_dir. What is happening is that no src files are found with this setup.cfg

```
[metadata]
name = example-pkg-YOUR-USERNAME-HERE
version = 0.0.1
author = Example Author
author_email = author@example.com
description = A small example package
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/pypa/sampleproject
project_urls =
    Bug Tracker = https://github.com/pypa/sampleproject/issues
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.6

[options.packages.find]
where = src
```

**Comment by bhrutledge** [comment]
@richtong I'm sorry to hear you're having trouble. This setup.cfg has worked for me and many others, but I'm happy to help clarify if needed. Can you tell us more about your environment? Specifically:

- Operating system
- Python version
- Directory structure of your project
- Commands you've executed and their output

Also, I don't quite understand what you mean by:

> the src directory is not picked up...What is happening is that no src files are found

Can you be more specific? What are you expecting? Are you getting error messages?

**Comment by pradyunsg** [comment]
Closing this due to lack of a response.
