### ISSUE TITLE
"sphinx" should be found in the docs

### ISSUE THREAD

**Issue by guettli** [pypa/packaging.python.org#101]
Since documentation of python packages is done with `sphinx` it should be mentioned somewhere.

But up to now it is not. See:
https://python-packaging-user-guide.readthedocs.org/en/latest/search.html?q=sphinx

Please add some information about sphinx.

A link to the sphinx docs is enough. Nobody needs a redundant copy of the sphinx docs.

**Comment by ncoghlan** [comment]
Sorry for the past radio silence here. I just closed #142 on the grounds of project templating tools being off-topic for distutils-sig, and hence off-topic for the packaging user guide.

Docs are slightly different, in that there *is* a packaging connection through the fact that we allows docs to be uploaded to pythonhosted.org, and we'd eventually like to let folks declare their docs build dependencies separately from their other dependencies. We've also discussed the idea of explicitly advising against using pythonhosted.org for project documentation, and instead recommending that folks use either Sphinx and ReadTheDocs, or else use static hosting on a site like GitHub Pages or BitBucket.

@dstufft, @qwcode - what do you think? Should we declare docs build and hosting recommendations in-scope for the packaging guide?

**Comment by dstufft** [comment]
Yes. Warehouse already tells people to use RTD when they hit the removed docs upload API.I've talked with @ericholscher about integration options between Warehouse <-> ReadTheDocs as well.

**Comment by Ivoz** [comment]
Maybe "Documenting your Project" (or similar) could be a heading under a new section, containing purely 'optional' advice on extra things to do with "developing a python project"; such as using SCM, using CIs, testing, etc

**Comment by anarcat** [comment]
hints on how to ship documentation for your project also seems like something i expected to see here. while i don't expect a full documentation tutorial (pointers are already included for that, i believe), it is tricky to figure out where to put the docs: should they be in the .egg file? should setup.py install them in the filesystem hierarchy? if i want to provide offline docs, how do i do that? or do we only want people to publish their docs online?

**Comment by hugovk** [comment]
There's now a tutorial covering the basics of creating docs using Sphinx with links for more info. 

https://packaging.python.org/tutorials/creating-documentation/

Is that enough to close this issue?

**Comment by pradyunsg** [comment]
Yes.
