### ISSUE TITLE
Update wheel tag note about Alpine Linux

### ISSUE THREAD

**Issue by ofek** [pypa/packaging.python.org#1011]
- https://packaging.python.org/specifications/platform-compatibility-tags/#platform-tags-for-other-nix-platforms
- https://github.com/pypa/packaging.python.org/blob/main/source/specifications/platform-compatibility-tags.rst#platform-tags-for-other-nix-platforms

Merged: https://github.com/pypa/auditwheel/issues/305

**Comment by daxamin** [comment]
I would like to help here and put together a PR, but it's not very clear to me what the updated note should be yet.
- Remove Alpine Linux from notes, since now `musllinux_1_1` is supported with Alpine?
- Add more info about `musllinux`?

Any guidance would be appreciated. Thanks!

**Comment by webknjaz** [comment]
Maybe also add musl to comparisons.

**Comment by jeanas** [comment]
Fixed by #1441.
