### ISSUE TITLE
Allow maintainers to merge their own PR's?

### ISSUE THREAD

**Issue by bhrutledge** [pypa/packaging.python.org#1096]
*Copied from https://github.com/pypa/packaging.python.org/pull/1091#issuecomment-1163045414 for discussion*

@pypa/packaging-user-guide-editors It looks like there's some configuration that prevents me (as a maintainer) from merging a PR that I authored without an approving review (which I can't give as the PR author). I'm wondering if this is the desired configuration. IE, would it be acceptable for maintainers to merge their own PRs?

cc @pradyunsg, because you seem to have some authority in here (per https://github.com/pypa/packaging.python.org/issues/926#issuecomment-876691583 and https://github.com/pypa/packaging.python.org/pull/1091#issuecomment-1163052745).

**Comment by pradyunsg** [comment]
I’ve exempted @pypa/packaging-user-guide-editors from the set of users who need an approval to merge their PRs, in this repository.
