### ISSUE TITLE
Hello, I would like to contribute to this documentation. Please let me know where I could start. Thank you!

### ISSUE THREAD

**Issue by Cachorro26** [pypa/packaging.python.org#1139]
Hello, I would like to contribute to this documentation. Please let me know where I could start. Thank you!

_Originally posted by @sdkdeepa in https://github.com/pypa/packaging.python.org/issues/194#issuecomment-913385848_

**Comment by bhrutledge** [comment]
Thanks! There's a contributing guide at https://packaging.python.org/en/latest/contribute/. If you have any more questions after reading, feel free to post them here.
