### ISSUE TITLE
Translation workflow fails with "nothing to commit"

### ISSUE THREAD

**Issue by bhrutledge** [pypa/packaging.python.org#1178]
For example: https://github.com/pypa/packaging.python.org/actions/runs/3627074405/jobs/6116629791 (in response to the daily "Test" run via #1175).

It also seems to be failing on PR's: https://github.com/pypa/packaging.python.org/pull/1177#issuecomment-1339366116.

@webknjaz @meowmeowmeowcat Can you take a look?

**Comment by meowmeowmeowcat** [comment]
Looks like it's due to these few lines: https://github.com/pypa/packaging.python.org/blob/0b2d1bc9adfd0f6f67292fbc2fa103c51ab494a8/.github/workflows/translation.yml#L3-L10

**Comment by bhrutledge** [comment]
Those lines have been there since #945 in August 2021, but these failures seem to have just started. Any idea why?

**Comment by webknjaz** [comment]
It's been happening since then. It needs to be fixed but has been low-priority.

**Comment by jeanas** [comment]
This has been fixed by @rffontenelle in #1435.
