### ISSUE TITLE
pyproject.toml - "Bug Tracker" example is not best

### ISSUE THREAD

**Issue by CarlFK** [pypa/packaging.python.org#1183]
Root of this: PyPi uses key names as human readable link text.   (maybe fine, maybe not, but not what this is about.)

This issue is about:
This example in packaging tutorials is valid but not best:

`"Bug Tracker" = "https://github.com/pypa/sampleproject/issues"`
 https://packaging.python.org/en/latest/tutorials/packaging-projects/#configuring-metadata

Toml spec says:
`Quoted keys follow the exact same rules as either basic strings or literal strings and allow you to use a much broader set of key names. Best practice is to use bare keys except when absolutely necessary.`
https://toml.io/en/v1.0.0#keys

Packaging docs:
``` 
urls
    type: table with keys and values of strings
A table of URLs where the key is the URL label and the value is the URL itself.
```
https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#urls

The use case for quoted keys is: pretty link text on PyPi.  
Here is an example in the wild:
https://pypi.org/project/ddb-cache/

There are 2 ways of making the example better: 
1. Follow toml best practice, remove the spacy key and use "Issues" (without quotes). 
2. Keep the example as is, add a note explaining the violation of toml best practice.  (PyPi uses the key...)

**Comment by jimustafa** [comment]
I think it may be a good idea to decide on a canonical set of labels for the common `Project-URL` used and maybe even make recommendations on the site to try and establish a standard. To that end, I have developed a small notebook at https://github.com/jimustafa/py-pkg-info-stats that can be used to determine the relative frequency of different `Project-URL` labels among the "top" packages on PyPI. Basically, what I find is that the following are the most commonly used labels in their respective class of `Project-URL`: `Homepage`, `Documentation`, `Changelog`, and `Source`. For links to the issue tracker, `Bug Tracker` is actually the most common, not unlikely the result of the guidance on https://packaging.python.org.
