### ISSUE TITLE
Replace `setup.py` mentions in "Packaging and distributing projects" guide with `pyproject.toml`, or merge guide with tutorial

### ISSUE THREAD

**Issue by astrojuanlu** [pypa/packaging.python.org#1205]
This guide https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/ still uses `setup.py` files, and in fact it doesn't actually mention `pyproject.toml` files at all.

I wonder though if, instead of updating the guide, it would just be better to remove it or merge it with the more up to date tutorial https://packaging.python.org/en/latest/tutorials/packaging-projects/ which was already updated as per gh-1084.

**Comment by bhrutledge** [comment]
I think this is a duplicate #887 and #792.
