### ISSUE TITLE
Quote extras to avoid problems with glob qualifiers in shells

### ISSUE THREAD

**Issue by matthewfeickert** [pypa/packaging.python.org#1209]
Some shells, like zsh, have glob qualifiers that will error if an extra is not quoted

```console
$ python -m pip install black[jupyter]
zsh: no matches found: black[jupyter]
$ python -m pip install --upgrade 'black[jupyter]'  # correct way without disabling globbing
```

Globbing can of course be turned off in these shells, but some users might not think of this right away.

At the moment all the extras in the packaging guide are unquoted:

https://github.com/pypa/packaging.python.org/blob/a103b5699eba73f0266044eeb8eecc6835642a3e/source/guides/installing-using-pip-and-virtual-environments.rst?plain=1#L295

https://github.com/pypa/packaging.python.org/blob/a103b5699eba73f0266044eeb8eecc6835642a3e/source/guides/installing-using-pip-and-virtual-environments.rst?plain=1#L301

https://github.com/pypa/packaging.python.org/blob/a103b5699eba73f0266044eeb8eecc6835642a3e/source/tutorials/installing-packages.rst?plain=1#L656-L658

https://github.com/pypa/packaging.python.org/blob/a103b5699eba73f0266044eeb8eecc6835642a3e/source/tutorials/installing-packages.rst?plain=1#L664-L666

Would a contribution that quotes all these be of interest? Or as this is not necessarily _required_ for installation of an extra should this not be added?

Tagging @pradyunsg on this as the same question [applies to `pip`'s docs](https://github.com/pypa/pip/blob/852deddb9c14afdb780e77ea28c2fa6d29f8c2e1/docs/html/cli/pip_install.rst?plain=1#L383-L403).

If this is of interest, I have a branch on my fork with this done already that I can PR.

**Comment by sinoroc** [comment]
I think this is would be a good improvement. Square brackets should be quoted. People get tripped up by this relatively often, I see this issue come up in StackOverflow from time to time.
