### ISSUE TITLE
stop recommending deprecated pkg_resources namespace packages

### ISSUE THREAD

**Issue by graingert** [pypa/packaging.python.org#1222]
The recommendations here are now outdated because plg_resources is deprecated: https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#creating-a-namespace-package

> This method is recommended if you need compatibility with packages already using this method or if your package needs to be zip-safe.

https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#pkg-resources-style-namespace-packages

> If you are creating a new distribution within an existing namespace package that uses this method then it’s recommended to continue using this as the different methods are not cross-compatible and it’s not advisable to try to migrate an existing package.

**Comment by webknjaz** [comment]
I don't think it's recommended. Just pointing out that old namespaces kinda don't have a choice.

**Comment by graingert** [comment]
Maybe the text could be updated to remove the mention of the obsolete zip-safe and say:

> This method is deprecated and not recommended unless you need compatibility with packages already using this method.

And then:
> Different methods are not cross-compatible to migrate an existing package all packages within the namespace must be migrated simultaneously.
