### ISSUE TITLE
Link to donations in footer is not visible

### ISSUE THREAD

**Issue by sinoroc** [pypa/packaging.python.org#1230]
In the footer, there is a link for donations:

>  The Python Software Foundation is a non-profit corporation. [Please donate.](https://www.python.org/psf/donations/)

but for me it is almost always obscured by a *Read The Docs* overlay element as can be seen in the following screenshot:

![image](https://user-images.githubusercontent.com/5529267/227956113-13989caa-8ae5-46d6-860f-5eb00149866a.png)

***References***:
* https://docs.readthedocs.io/en/stable/flyout-menu.html

***Related***:
* https://github.com/pypa/pypa-docs-theme/issues/22

**Comment by webknjaz** [comment]
Sounds like this should be fixed in the upstream theme.

**Comment by chrysle** [comment]
Closing as unneeded since the migration to Furo.
