### ISSUE TITLE
Definition of the initial population for the genetic algorithm by the user

### ISSUE THREAD

**Issue by zsbeheshti** [pypa/packaging.python.org#1235]
Dear all,

I am using Python's pypi genetic algorithm 1.0.2 and I want to run this genetic algorithm with my default initial population. How can I do this?

And is it possible that, for example, out of 70 populations, I introduce only one and the genetic algorithm produces the other 69?

Regards

**Comment by jeanas** [comment]
I'm going to close this issue, since it is not related to the Python Packaging User Guide. Please use https://discuss.python.org/ for general Python questions, or, as Anderson said, contact the maintainers of the package you're using directly.
