### ISSUE TITLE
State of development of the guide

### ISSUE THREAD

**Issue by chrysle** [pypa/packaging.python.org#1253]
There are quite a few open pull requests and issues that have been open for a long time and have not been adressed yet.

Are there more maintainers for the guide needed? If so, I'd recommend initiating a call and giving long-time contributors the chance to help out.

**Comment by bhrutledge** [comment]
Thanks for opening this, @chrysle. I'm nominally a maintainer of this ([since 2021](https://github.com/pypa/packaging.python.org/issues/926)), but have had to deprioritize it, and I'm not in a position to find new maintainers. That said, I appreciate the contributions you've made lately.

cc @pypa/packaging-user-guide-editors @pradyunsg

**Comment by webknjaz** [comment]
+1 from me

@di let's invite @chrysle to the repo. He's been active in other projects I'm involved in lately, not just PyPUG. This project could benefit from letting him review and merge stuff..

**Comment by chrysle** [comment]
Thank you for valuing my work!

Maybe we can also ask @sinoroc and @abravalheri if they want to help?

**Comment by webknjaz** [comment]
Pretty sure they have their hands full with other stuff..

**Comment by sinoroc** [comment]
> Maybe we can also ask @sinoroc and @abravalheri if they want to help?

The time window where I was able to contribute has now closed. But I am glad to see the bottleneck loosening up a bit. I had some other contributions planned (before PRs merges got stalled), I might get back to it at a later point. Thanks :)

**Comment by webknjaz** [comment]
Pinging @di once more... This repo really needs more hands and @chrysle has just completed a huge multi-months guide refactor. Can we give them more privileges here?

**Comment by di** [comment]
I'm in favor. Can any of the other @pypa/packaging-user-guide-editors weigh in?

**Comment by pradyunsg** [comment]
I'm on board as well.

**Comment by bhrutledge** [comment]
Yep, happy to have the help.

**Comment by webknjaz** [comment]
@di @pradyunsg now that everybody's in favor, could you send the invitation? I don't think anybody else has enough privileges for that.

**Comment by chrysle** [comment]
Thank you all for your confidence! I'll try doing my best.
