### ISSUE TITLE
Guide for "Single sourcing the package version" refers to setup.py

### ISSUE THREAD

**Issue by venthur** [pypa/packaging.python.org#1260]
https://packaging.python.org/en/latest/guides/single-sourcing-package-version/ refers to setup.py and the many ways how to get the version into setup.py. pyproject.toml is mentioned only as a side note.

Since setup.py is deprecated in favour of pyproject.toml, I wonder what to do with this document. Single sourcing the version should be a non-issue. We could either strip the whole document down to pyproject.toml which would make the document very small, or move the relevant paragraph into the packaging tutorial:

> ```toml
> [project]
> name = "package"
> dynamic = ["version"]
> 
> [tool.setuptools.dynamic]
> version = {attr = "package.__version__"}
> ```

**Comment by chrysle** [comment]
> https://packaging.python.org/en/latest/guides/single-sourcing-package-version/ refers to setup.py and the many ways how to get the version into setup.py. pyproject.toml is mentioned only as a side note.
> 
> Since setup.py is deprecated in favour of pyproject.toml, I wonder what to do with this document.

`setup.py` isn't deprecated that long, and many projects are still using it. I'm for keeping the page as-is.

**Comment by webknjaz** [comment]
FWIW `setup.py` isn't deprecated **at all**. What's discouraged is calling it directly as a script. Using it through the standard PEP 517 interface is perfectly valid use.

**Comment by chrysle** [comment]
> FWIW `setup.py` isn't deprecated **at all**. What's discouraged is calling it directly as a script.

There's some excellent [lecture](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html) about this, maybe this can be linked?

> It would be nice, however, to swap the preference in the document.

Preference for _what_ do you mean?

**Comment by wimglenn** [comment]
@webknjaz To correct some misconceptions:

`pyproject.toml` is not labelled as _beta_ in setuptools. It is support for declaring configurations not standardized by [PEP 621](https://peps.python.org/pep-0621/) that is still in beta stage. [version](https://peps.python.org/pep-0621/#version) is not one of those fields.

The plan from setuptools is to eventually deprecate [`setup.cfg`](https://github.com/pypa/setuptools/issues/3214), so its use should not be recommended in the packaging guide.

+1 for moving `pyproject.toml` example to the top, the existing `setup.py` example is quite crufty and hacky.

**Comment by ChrisBarker-NOAA** [comment]
thin the page needs updating:

See https://github.com/pypa/packaging.python.org/pull/1273

Please comment / edit that so we can get a nicer page together.

**Comment by ncoghlan** [comment]
Resolved in #1612
