### ISSUE TITLE
Update reference to distutils

### ISSUE THREAD

**Issue by hauntsaninja** [pypa/packaging.python.org#1286]
https://packaging.python.org/en/latest/specifications/platform-compatibility-tags/#platform-tag needs an alternative to `distutils.util.get_platform()`

**Comment by MohsenAAkeel** [comment]
`sysconfig.get_platform()` [seems to be a good alternative](https://github.com/python/cpython/blob/main/Lib/sysconfig.py#L747). The code is nearly identical, the only difference being distutils accesses the windows environment variable `VSCMD_ARG_TGT_ARCH`. The result of that seems, at this point in time, to be immaterial given [how it's used](https://github.com/python/cpython/blob/main/Tools/c-analyzer/distutils/util.py#L100). It could give a different result compared to sysconfig at some point, but I think distutils deprecation prevents that becoming an issue.

If that seems a suitable alternative, happy to make an update on the platform tags page.

**Comment by chrysle** [comment]
By the way, [this here](https://packaging.python.org/en/latest/key_projects/#distutils) will also need an update. I think it should be removed completely.

**Comment by sinoroc** [comment]
> By the way, [this here](https://packaging.python.org/en/latest/key_projects/#distutils) will also need an update. I think it should be removed completely.

People will still see references to *distutils* and will want to know what it was. So I do not think it should be removed. Updated for sure, but not removed.

**Comment by chrysle** [comment]
> If that seems a suitable alternative, happy to make an update on the platform tags page.

Sure, please do it!
