### ISSUE TITLE
'Upload artifact signatures to GitHub Release' - gh release step fails

### ISSUE THREAD

**Issue by matthewhegarty** [pypa/packaging.python.org#1304]
Refering to the guide [here](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/)

For the step 'Upload artifact signatures to GitHub Release' it's not clear that this step will only succeed if the release has already been created on github (i.e. manually or by another process).  If the release is not present, then ['release not found'](https://github.com/cli/cli/blob/ec4935946714159c90d9eca1acf95410d20aaa20/pkg/cmd/release/shared/fetch.go#L234) will be displayed.

It's possible that the preferable action would be to create a release using ['gh release create'](https://cli.github.com/manual/gh_release_create)

**Comment by webknjaz** [comment]
Thanks for the report! The guide has recently been updated in https://github.com/pypa/packaging.python.org/pull/1261 and in was suggested that it should avoid using a third party action in favor of the GH CLI that's always available and official.

Apparently, we overlooked this bit.

@sirosen @chrysle could you look into fixing the problem?

**Comment by sirosen** [comment]
I have not been able to make time to get involved in fixing this, even though I would like to.

As the most temporary of stopgaps, if anyone sees this issue, here's a config which I have which is known working in a current project, very similar to the existing documentation (but notably missing the sigstore step):
https://github.com/python-jsonschema/check-jsonschema/blob/main/.github/workflows/publish_to_pypi.yaml

That workflow gives us the workflow event/trigger declaration for "release published", if nothing else.

`gh release create` could work, but I worry about the level of control that most users will have over the release notes if that's the only documented option. Even with a relatively simple strategy like "collect the top section of the changelog and reformat it from rst to md", there are a lot of steps which are hard to get right.

**Comment by chrysle** [comment]
I'll draft a fix and will notify you once I'm done.

**Comment by webknjaz** [comment]
> The PyPI publishing workflow triggers on pushing a tagged commit, and this is the follow-up. However I'm in favour of the second variant, since `gh release create` is an interactive process, which requires a lot of settings.

I'd rather not change the trigger in the workflow right now. Maybe we could make a simple CLI call to make a release without a body? Just a title derived from the version tag? My preference is `workflow_dispatch` and the release creation after it's know that the PyPI upload actually succeeded, but I'd like to put such a complicated workflow into a separate guide.
