### ISSUE TITLE
Clarify `__init__.py` syntax in namespace packaging guide

### ISSUE THREAD

**Issue by pawamoy** [pypa/packaging.python.org#1305]
The [docs](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/) say:

> The __init__.py file for the namespace package needs to contain only the following:
> Every distribution that uses the namespace package must include an identical __init__.py

I wonder:

1. does "only" mean "a semantically equivalent set of instructions that appear first in the file"?
2. does "identical" mean "semantically equivalent" or "character-by-character identical"?

To give an example, consider the two following `__init__.py` modules. Are they valid paired-modules for a non-native namespace package?

```python
# arbitrary comments like:
# pylint: disable=missing-module-docstring
__path__ = __import__("pkgutil").extend_path(__path__, __name__) # type: ignore
# note the type ignore comment as well
```

```python
from pkgutil import extend_path
__path__ = extend_path(__path__, __name__)
```

Note how neither the textual contents nor the AST is the same, but how they actually do the same thing.

Does it still work if there are other statements after extending `__path__`?

```python
from pkgutil import extend_path
__path__ = extend_path(__path__, __name__)
print("done extending __path__")
```

Don't hesitate to redirect me to the code responsible for this :slightly_smiling_face:

**Comment by chrysle** [comment]
> Should I open the exact same issue on https://github.com/pypa/packaging.python.org? 

Everything is possible with modern technology™!

> I see that you're
> 
> > looking into an overhaul of the guide
> 
> so that might not be necessary? Maybe easier for you to track if it's over there. Let me know!

With all your testing experience, I think you could do it even better than me! I'm also mostly aiming to cover some additional information (mostly from the [setuptools docs](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html)).

> In the meantime I'll run some experiments.

Thanks a lot for extensive testing!
