### ISSUE TITLE
Update Sphinx theme

### ISSUE THREAD

**Issue by willingc** [pypa/packaging.python.org#1354]
The current Sphinx theme lacks a right-hand sidebar for page navigation. It would be lovely to move to something similar to the  devguide.python.org theme, Furo, or ???

cc/ @pradyunsg

**Comment by webknjaz** [comment]
https://github.com/pypa/packaging.python.org/pull/791

**Comment by pradyunsg** [comment]
I think I'm no longer opposed to Furo being used here, albeit we might have to spend some time after to clean up some of the rough edges that migration will pop up.

**Comment by webknjaz** [comment]
I'll rebase the PR, then.

**Comment by pradyunsg** [comment]
Done in #791.
