### ISSUE TITLE
Stop deleting documentation build directory on rebuilds

### ISSUE THREAD

**Issue by jeanas** [pypa/packaging.python.org#1363]
`noxfile.py` currently contains this in the `build` session:

```python
    shutil.rmtree(target_build_dir, ignore_errors=True)
```

This nukes the build folder before proceeding.

I currently have to work on a relatively slow Internet connection. Each build is re-downloading the inventory files, which takes noticeable time.

Is there any particular reason not to use Sphinx's incremental build capabilities? After all, it's easy enough to remove the build folder by hand if you want to check that some oddity is not caused by incremental builds.

**Comment by pradyunsg** [comment]
Could you file a PR for removing this?

**Comment by pradyunsg** [comment]
Quick bit of git archaeology suggests that this was added in https://github.com/pypa/packaging.python.org/pull/591.

I'm a bit wary of Sphinx's incremental builds, especially with how they tend to not do too well when the page hasn't been modified but other pages that depend on it have been modified (eg: due to the toctree being included in the page). Let's remove this though, and see if that's a source of issues. :)

**Comment by webknjaz** [comment]
+1 drop this and let Sphinx use its cache. It's good in general, except when the extensions forget to implement dependencies. This will allow the local build speedup, while RTD will still build from scratch anyway...

**Comment by webknjaz** [comment]
@jeanas are you sure the inventory files end up in that specific dir, though? I thought the doctrees would be there..

**Comment by pradyunsg** [comment]
> @jeanas are you sure the inventory files end up in that specific dir, though?

From the [documentation](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#module-sphinx.ext.intersphinx)...

> This will download the corresponding objects.inv file from the Internet and generate links to the pages under the given URI. The downloaded inventory is cached in the Sphinx environment, so it must be re-downloaded whenever you do a full rebuild.

So, it should be cached in the build directory.

**Comment by webknjaz** [comment]
I think the build dir only contains HTML and inventory would go into the doctree cache, which is separate. If it's provided, that is. The docs say "build env", not "build dir", which is a bit confusing.

Also, in my experience, Sphinx still attempts to download stuff, but it's possible to manually cache said files, a-la pydoctor.

**Comment by webknjaz** [comment]
Pretty sure the core of the slowdown is related to not setting the doctrees dir, additionally to removing the build dir.
