### ISSUE TITLE
Issue with tabs in guide "Install packages in a virtual environment using pip and venv"

### ISSUE THREAD

**Issue by sinoroc** [pypa/packaging.python.org#1375]
I wonder if it would not be better to have 3 tabs all the way. Unix and Mac are merged into 1 tab except in the "[_Prepare pip_](https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/#prepare-pip)" section. So the auto switch of tabs throughout the page does not work as expected.

_Originally posted by @sinoroc in https://github.com/pypa/packaging.python.org/issues/1338#issuecomment-1796293328_

**Comment by chrysle** [comment]
I agree with that. A PR fixing this is welcome!
