### ISSUE TITLE
Read The Docs seems to not build pull requests any longer

### ISSUE THREAD

**Issue by sinoroc** [pypa/packaging.python.org#1393]
Read The Docs seems to not build pull requests any longer.

I do not see builds for these 2 recent pull requests:

* https://github.com/pypa/packaging.python.org/pull/1391
* https://github.com/pypa/packaging.python.org/pull/1392

**Comment by chrysle** [comment]
Whoops, duplicated in just this second ;-)

**Comment by willingc** [comment]
@pradyunsg It's difficult to troubleshoot the RTD since I can't see the full configuration.

I wonder if the codespell fix broke this though it seems unrelated but 🤷🏼‍♀️

**Comment by chrysle** [comment]
> Looks like this is back? It worked on #1397.

Yes, closing.
