### ISSUE TITLE
Put a tag from time to time to the Python Packaging User Guide?

### ISSUE THREAD

**Issue by fconil** [pypa/packaging.python.org#1399]
hi,
I was wondering if you could put a tag from time to time on the Python Packaging User Guide.
May be a [calendar versionning](https://calver.org/) tag ?
It could enable going back and forth in the documentation on Read The Docs.
Thanks to the team

**Comment by willingc** [comment]
@fconil I think that would be a helpful thing to do. What do other folks think? Monthly might be a good cadence.

**Comment by willingc** [comment]
Related to #1390

**Comment by pradyunsg** [comment]
I'm not sure I understand why this is being requested. @fconil Could you clarify what use-case/problem this solves?

> It could enable going back and forth in the documentation on Read The Docs.

Is there a specific reason you want to do this?

My concern is that if we're doing tags regularly, there's going to be lots of pages with the same content on the domain and I'm mildly concerned about the SEO effects that'd have; the domain currently has decent SEO reputation and having duplicated content will make it difficult to ensure that it stays that way and that users are directed to the latest page as often as possible.

Certain things might be better covered via looking at the git history or us actually maintaining a proper changelog.

**Comment by fconil** [comment]
I am diving into packaging as I am asked some choices and advices on our project. I am trying to write what I have understood and the steps to follow.

I made some links to the documentation and I discovered [Writing your pyproject.toml](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#writing-pyproject-toml) that I did not saw at the beginning.
So I was wondering when it was made and how I missed it. That's how I went to this repository and found this was a new page created this month. That why I thought a tag could be useful : these are the 2023 instructions, for example. It could help making a diff between two tags to know what was changed.

I also saw an issue (#1382) for moving a page I referenced, which is something that happen. I was reading a blog post on packaging history which had a broken link to [distutils](https://docs.python.org/3/distutils), knowing `distutils` has been removed in Python 3.12, I went to [distutils (Python 3.11)](https://docs.python.org/3.11/distutils/) page.

I have no knowledge on SEO problems. My issue is just a suggestion not a criticism, I thought it would be less work than a writing a changelog. If you don't find it useful, I learned how to diff with dates :)

**Comment by sinoroc** [comment]
There is also [this thread](https://github.com/pypa/packaging.python.org/issues/1384) about adding some kind of changelog. Would that help?

I do not know if @fconil wants the older versions to be available as built and published pages, or if having the tags on the git repository would be enough.

> there's going to be lots of pages with the same content on the domain and I'm mildly concerned about the SEO effects that'd have; the domain currently has decent SEO reputation and having duplicated content will make it difficult to ensure that it stays that way

What if the older versions are available only on a different domain (on `readthedocs.org` for example)? Is that possible? Would that be potentially less damaging from a SEO point of view?


All in all, I think there is some value in having some kind of history somewhere. But I do not know how to realize this. Changelog, keeping the old versions published, never delete pages (but only unlink them and mark them as deprecated)... all seem to have some cons that might be bigger than the pros.

**Comment by fconil** [comment]
> I do not know if @fconil wants the older versions to be available as built and published pages, or if having the tags on the git repository would be enough.

Ideally, yes, I would like to read published pages for some points in time. That way, one can see "Ok this were the instructions 2 years ago but now it has changed".

**Comment by sinoroc** [comment]
I guess this also a solution: https://web.archive.org/web/20230000000000*/https://packaging.python.org/

**Comment by fconil** [comment]
> I guess this also a solution: https://web.archive.org/web/20230000000000*/https://packaging.python.org/

It could be a workaround, but I prefer diff and blame.

I see nothing to add that could be useful to this discussion, should I close the issue or you prefer to do it ?

**Comment by pradyunsg** [comment]
I'll go ahead and close this out -- thanks for the suggestion! 

---

For posterity, the way you can a date-based diff with the GitHub UI is to use [Git's `@{date}` syntax](https://git-scm.com/docs/gitrevisions#Documentation/gitrevisions.txt-emltrefnamegtltdategtemegemmasteryesterdayememHEAD5minutesagoem) for revision ranges. For example, below is a link to all commits since 2023-01-01:

[https://github.com/pypa/packaging.python.org/compare/main@{2023-01-01}...main](https://github.com/pypa/packaging.python.org/compare/main@%7B2023-01-01%7D...main)

Using the [3 dot syntax](https://stackoverflow.com/a/24186641/1931274) here shows all the commits on the GitHub.com UI as of the time of posting this comment.
