### ISSUE TITLE
Description of virtualenv in key_projects.rst is clunky and outdated

### ISSUE THREAD

**Issue by zahlman** [pypa/packaging.python.org#1406]
Current versions of virtualenv don't support Python 2.7, contrary to what the guide currently claims. I also found the prose for this description redundant and unclear.

I have locally cloned the repository, and I have made and verified changes to fix these issues; however, I (understandably) don't have rights to push my local branch to the SSH origin. How exactly is submitting a pull request intended to work?

**Comment by zahlman** [comment]
Sorry about that, I figured it out, see https://github.com/pypa/packaging.python.org/pull/1407

**Comment by willingc** [comment]
Closed by #1407
