### ISSUE TITLE
Minor mis-spelling in documentation

### ISSUE THREAD

**Issue by mg104** [pypa/packaging.python.org#1416]
Minor mis-spelling of "then" as "than" in the documentation URL: `https://packaging.python.org/en/latest/specifications/version-specifiers/#version-specifiers`, in the section starting as follows:

<pre>
Prefix matching may be requested instead of strict comparison, by appending a trailing .* to the version identifier 
in the version matching clause. This means that additional trailing segments will be ignored when determining whether 
or not a version identifier matches the clause. If the specified version includes only a release 
segment, <b>than</b> trailing components (or the lack thereof) in the release segment are also ignored.
</pre>

**Comment by mg104** [comment]
Hi, thanks for the quick reply! I would like to open a PR but I'm in the process of learning how to submit PRs, since I'm a "newbie" :). Please let me know if I can take some time to make the PR? Thanks.

**Comment by jeanas** [comment]
@mg104 Do you need any help?

**Comment by mg104** [comment]
Hi @jeanas, my apologies for being so late. Would it be ok if you could assign this to someone else? Thanks.

**Comment by sinoroc** [comment]
@jeanas Looks like this can be closed now. Not sure why GitHub did not close it automatically when https://github.com/pypa/packaging.python.org/pull/1451 got merged.
