### ISSUE TITLE
setup_requires

### ISSUE THREAD

**Issue by qwcode** [pypa/packaging.python.org#143]
things to cover
- delayed/nested imports (e.g. http://pytest.org/latest/goodpractises.html#integration-with-setuptools-test-commands)
- 3rd party workaround: https://bitbucket.org/dholth/setup-requires
- pip's plan to take control of setup_requires processing
- PEP426 replacements...
- https://pip.pypa.io/en/latest/reference/pip_install.html#controlling-setup-requires

**Comment by jeanas** [comment]
Closing this since `setup_requires` has been obsoleted by PEP 518.
