### ISSUE TITLE
Avoid the intersphinx mapping to ourselves?

### ISSUE THREAD

**Issue by jeanas** [pypa/packaging.python.org#1438]
After the merge of #1396, builds started to fail with errors about undefined references, which was normal because some labels were removed that indeed had references pointing to them. (This was fixed in #1433.) The problem is that this was not caught before the merge, even though the GitHub merge queue was used to merge the PR. The merge queue is supposed to check the result of merging the PR branch into master (as opposed to just checking the PR branch).

I did some digging into this mystery and it seems to me that this was caused by this oddity in our `conf.py`:

```python
intersphinx_mapping = {
    # ...
    "packaging.python.org": ("https://packaging.python.org/en/latest/", None),
    # ...
}
```

So... what happened is that while the PR was not merged, the references `` :ref:`declaring-build-dependencies` `` was resolved to to be an Intersphinx reference to the deployment https://packaging.python.org ! And then, after the PR got merged, the targets were removed by the deployment and the references logically became dangling.

You can see this on the PR preview of #1396:

https://python-packaging-user-guide--1396.org.readthedocs.build/en/1396/guides/modernize-setup-py-project/

![image](https://github.com/pypa/packaging.python.org/assets/37271310/39904648-3d24-4624-9fc8-8d40471cc0b0)

Here I'm hovering on the first link, which points to inside the PR preview.

![image](https://github.com/pypa/packaging.python.org/assets/37271310/de1a6bcd-5ef9-4de8-9c83-694b80224040)

And here I hover on the second link, which points to https://packaging.python.org instead, with a tooltip indicating an external link.

I'm going to open a PR to remove that entry in the Intersphinx mapping.

**Comment by hugovk** [comment]
Oh, that's tricky one! Good work tracking it down!
