### ISSUE TITLE
Request for triage rights

### ISSUE THREAD

**Issue by jeanas** [pypa/packaging.python.org#1446]
I see quite a few issues that could be closed to tidy up the tracker a bit. For example, #1235 is not a packaging problem, #709 was done in #1368, and #143 is obsolete now that `setup_requires` has been replaced with `pyproject.toml`'s `build-system.requires`.

Rather than commenting on all such issues I find, I'm going to fight impostor's syndrome and ask if you would find appropriate to give me triage rights. I won't be vexed if the answer is “no”, though.

**Comment by webknjaz** [comment]
@di @pradyunsg can we add them to gardeners, at least?

**Comment by di** [comment]
Added @jeanas to @pypa/gardeners!

**Comment by jeanas** [comment]
Thank you all! I will do my best to use the role wisely.
