### ISSUE TITLE
Wrongly reference to PEP-529 in PEP-691

### ISSUE THREAD

**Issue by ProFatXuanAll** [pypa/packaging.python.org#1622]
I believe that all the references to [PEP-529](https://peps.python.org/pep-0529/) in [PEP-691](https://peps.python.org/pep-0691/) should be [PEP-592](https://peps.python.org/pep-0592/).

**Comment by sinoroc** [comment]
Oh! You might be right...

But I think it should rather be reported over there on the [PEPs repository](https://github.com/python/peps/issues).

**Comment by ProFatXuanAll** [comment]
I have opened the same issue on the [PEPs repository](https://github.com/python/peps/issues/4088).
Should I close this issue now or wait until the [issue](https://github.com/python/peps/issues/4088) get resolved?

**Comment by sinoroc** [comment]
> Should I close this issue now or wait until the [issue](https://github.com/python/peps/issues/4088) get resolved?

I would close.
