### ISSUE TITLE
[tracking] new tutorials and other revisions

### ISSUE THREAD

**Issue by ddbeck** [pypa/packaging.python.org#194]
This issue is to track work on writing new, introductory tutorials for the guide, and other activities that are part of an effort to expand and revise the guide. [See this thread from the distutils-sig](https://mail.python.org/pipermail/distutils-sig/2015-November/027776.html) for more details about this project. Work on these tutorials will (at least initially) take place on the `develop` branch.

I am inviting the group of volunteers to use this issue to see what other issues are available and to use this as a place for general questions and help (i.e., questions that are not issue-specific), to minimize noise on other issues and the creation of new issues.

If you'd like to contribute to these sections, please see the (to be) linked issues for details. Additionally, please review the [developing guide to contributing](https://packaging.python.org/contribute/). If you start work on an issue, please consider saying so on the relevant issue, so others don't duplicate your work. Thanks!
## Outline

Broadly, the new intro to packaging tutorials have the following outline:
1. [Who is this for?](https://github.com/pypa/python-packaging-user-guide/issues/195)
2. [Prerequisites](https://github.com/pypa/python-packaging-user-guide/issues/196)
3. [What's a package?](https://github.com/pypa/python-packaging-user-guide/issues/199)
4. [Where do packages come from?](https://github.com/pypa/python-packaging-user-guide/issues/200)
5. [Install your first package](https://github.com/pypa/python-packaging-user-guide/issues/201)
6. [Use a virtual environment](https://github.com/pypa/python-packaging-user-guide/issues/202)
7. [Make your first package](https://github.com/pypa/python-packaging-user-guide/issues/203)
8. [Publish your first package](https://github.com/pypa/python-packaging-user-guide/issues/204)

Issues will soon be created to address each section specifically; the outline above will link to each section's issue.
## Bite size tasks
- #207: Add build instructions to the README
## Extra style notes

The intro to packaging tutorials have some extra style considerations on top of that of the guide generally:
- In contrast to more task-focused writing, the tutorials are meant to build fundamental packaging skills, rather than resolve a specific problem. With that in mind, try to invite readers to learn to do something without regard for its specific applications. So instead of something like "Read this section if you want to share a package…" try "After you complete this section, you'll be able to share a package…"

**Comment by souravsingh** [comment]
I would like to work on the first two parts of the tutorial.

**Comment by ddbeck** [comment]
@souravsingh That's great! I would suggest picking one to begin with and, as you make progress, mention that you're working on it in the section-specific issue (so others don't duplicate your work). Let me know if you have any questions. Thanks!

**Comment by thatdocslady** [comment]
I'll be happy to help with content reviews (proofreading, editing) and overall structure, unfortunately I don't have enough bandwidth at the moment to write content from scratch :-( feel free to assign any content that needs review to me :-)

**Comment by souravsingh** [comment]
Thanks for the help @thatdocslady

**Comment by alexwlchan** [comment]
Like thatdocslady, I'm happy to take on review tasks if it's useful, but I can't promise any original content (things are all a bit up-in-the-air at the moment).

**Comment by ddbeck** [comment]
@thatdocslady @alexwlchan thank you both for volunteering. As sections become stable, I'll definitely call on you to be a new set of eyes.

**Comment by dsmatlak** [comment]
I want to learn about Python and participate in this project by either writing, researching, or proofreading. If you have any suggestions for a Python newbie, please let me know. Thanks :)

**Comment by ddbeck** [comment]
@dsmatlak Great, I think you're in the right place. Since you're new to Python, I think it would be a big help if you could test out the new tutorial sections as they are written. I'm also planning to work on writing up some bite-size issues that might be a little more manageable than writing a whole new section. I'm planning to tag issues soon and update here when we get to that point. Thanks for your interest!

**Comment by dsmatlak** [comment]
@ddbeck Excellent, sounds good.

**Comment by JoshuaAcosta** [comment]
@ddbeck Now that finals are over, I can dedicate my time to this project.  I've forked the project but unsure what to do next (this is my first time contributing to OS project). Do I create a branch locally, write the documentation for assigned section (#196)  then once I'm done, submit a pull request to the develop branch? Is there a link to a resource I can check out about this? I appreciate the opportunity and the help!

**Comment by azibit** [comment]
Woow, Just came across this issue and I would really love to be of help

**Comment by ddbeck** [comment]
@azibit thanks for your interest! This has fallen by the wayside a little bit, but I'll have more time to work on this project in the next couple weeks, I expect. Take a look at some of the issues linked from the outline and see if there's something specific you'd like to work on. Happy to provide any specific guidance or help, as needed.

**Comment by jonfujita** [comment]
I'd love to contribute a bit to this. I'm doing a bootcamp and would like to practice adding to documentation and potentially some code. Thanks.

**Comment by jonparrott** [comment]
@jonfujita as mentioned in @ddbeck's comment, this has fallen a bit by the wayside but if there's any particular topic you want to pursue let us know and we can provide some guidance.

**Comment by ddbeck** [comment]
@jonparrott Oh jeez that couple weeks thing was… optimistic. I've noticed you've brought on a lot of activity on the repo, triaging open issues and PRs. Did you have any long term plans that I can coordinate with (or at least not get in the way of), especially when it comes to these tutorials?

**Comment by jonparrott** [comment]
@ddbeck still getting my head around all of this so I'm doing some baby steps (both for my own benefit and to not rustle feathers by changing everything at one). I'll let you know once I'm a bit more comfortable (and feel free to nag me).

**Comment by aryan-harsh** [comment]
@ddbeck @theacodes is there any work left to do? can i help in any way. i do not know much of python, but am good with content writing.

**Comment by Venu-Gopal18** [comment]
@ddbeck  I am good at content writing and well aware of python . Is there anything I can do? I want to be participate as active as possible cuz I'm new

**Comment by lorarjohns** [comment]
I'd love to contribute content on virtual environments.

I can also get into managing and deploying packages with Docker Compose; pytest and Fabric/GitHub CI/CD workflows with VSCode, and packaging vs 'developing' for different tools and different objectives, if you like. I have a teaching and research background and really enjoy making tutorials 😄

**Comment by Lawrence-Krukrubo** [comment]
Hey guys, how can I contribute. I'm a top writer in Artificial intelligence in the Medium and I love to code. please let me know where I can best fit in

**Comment by ihzarizkyk** [comment]
how to make the first package? ...

**Comment by yufi1213** [comment]
https://github.com/pypa/packaging.python.org/issues/194#issuecomment-653201984

**Comment by rneelas** [comment]
@ddbeck is there any open tutorials to which I can contribute? Please do let me know, more happy to write up

**Comment by freek-sonal** [comment]
@ddbeck i would like to start contributing in open source. And while learning, i wanted to contribute in writing tutorials. Please let me know if you have any work i can contribute to.

**Comment by dayvheed** [comment]
Hi @ddbeck. I am a technical content writer that has written a couple of blog tutorials in Python and ML. I would love to contribute to this project in any way possible. Please let me know if there's something I can do

**Comment by webknjaz** [comment]
@dayvheed there's a recently requested package deprecation guide: https://github.com/pypa/packaging.python.org/issues/883. Do you want to propose a PR on this topic? There's pointers in that issue one could start exploring and converting into an RST file.

**Comment by dayvheed** [comment]
@webknjaz thanks a lot. I just checked it out. So if I get the thread right, the author wants to inform users that manimce is obsolete and manim should rather be installed. 

I can then write a documentation of the things around this development. Is that correct please?

**Comment by webknjaz** [comment]
Yep. That's right, also let's move the discussion related to the specific guide to that document or to a PR — if you want to start with submitting an unfinished draft and update it as you add new things there. You may want to take a look at other guides and attempt to match that style.

**Comment by dayvheed** [comment]
Thank you. I have moved further discussions there.

**Comment by msanazi22** [comment]
Hi

**Comment by sdkdeepa** [comment]
Hello, I would like to contribute to this documentation. Please let me know where I could start. Thank you!

**Comment by TarunavBA** [comment]
> Hello, I would like to contribute to this documentation. Please let me know where I could start. Thank you!

@sdkdeepa let me know if you can help to my projects. You can [mail](mailto:tarunavba@gmail.com) me. I would feel very happy if you can help me in my python project.

**Comment by joyjoseph** [comment]
I would love to be part of this. please how do I contribute?

**Comment by pradyunsg** [comment]
Hi folks! If you're interested in contributing to this documentation, please see the [issues labelled as good first issue](https://github.com/pypa/packaging.python.org/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22).

I'm going to go ahead and close this one, since (a) there are tracking issues for each individual part of this issue and (b) I'm pretty sure most of the current maintainers do not have the context necessary to know what this issue was scoped as originally.

**Comment by navaneethnpk** [comment]
Hi, I am an open-source enthusiast. It is difficult to start contributing to open-source projects because it's way too many. I came here from a blog post. I would love to join this community and contribute. Please let me know what to do. Thanks 😄

**Comment by mohdzahidabdullah** [comment]
> This issue is to track work on writing new, introductory tutorials for the guide, and other activities that are part of an effort to expand and revise the guide. [See this thread from the distutils-sig](https://mail.python.org/pipermail/distutils-sig/2015-November/027776.html) for more details about this project. Work on these tutorials will (at least initially) take place on the `develop` branch.
> 
> I am inviting the group of volunteers to use this issue to see what other issues are available and to use this as a place for general questions and help (i.e., questions that are not issue-specific), to minimize noise on other issues and the creation of new issues.
> 
> If you'd like to contribute to these sections, please see the (to be) linked issues for details. Additionally, please review the [developing guide to contributing](https://packaging.python.org/contribute/). If you start work on an issue, please consider saying so on the relevant issue, so others don't duplicate your work. Thanks!
> 
> ## Outline
> Broadly, the new intro to packaging tutorials have the following outline:
> 
> 1. [Who is this for?](https://github.com/pypa/python-packaging-user-guide/issues/195)
> 2. [Prerequisites](https://github.com/pypa/python-packaging-user-guide/issues/196)
> 3. [What's a package?](https://github.com/pypa/python-packaging-user-guide/issues/199)
> 4. [Where do packages come from?](https://github.com/pypa/python-packaging-user-guide/issues/200)
> 5. [Install your first package](https://github.com/pypa/python-packaging-user-guide/issues/201)
> 6. [Use a virtual environment](https://github.com/pypa/python-packaging-user-guide/issues/202)
> 7. [Make your first package](https://github.com/pypa/python-packaging-user-guide/issues/203)
> 8. [Publish your first package](https://github.com/pypa/python-packaging-user-guide/issues/204)
> 
> Issues will soon be created to address each section specifically; the outline above will link to each section's issue.
> 
> ## Bite size tasks
> * [Add build instructions to the README #207](https://github.com/pypa/packaging.python.org/issues/207): Add build instructions to the README
> 
> ## Extra style notes
> The intro to packaging tutorials have some extra style considerations on top of that of the guide generally:
> 
> * In contrast to more task-focused writing, the tutorials are meant to build fundamental packaging skills, rather than resolve a specific problem. With that in mind, try to invite readers to learn to do something without regard for its specific applications. So instead of something like "Read this section if you want to share a package…" try "After you complete this section, you'll be able to share a package…"

**Comment by mohdzahidabdullah** [comment]
https://github.com/pypa/packaging.python.org/issues/194#issue-120272376

**Comment by Kongpcmail** [comment]
> This issue is to track work on writing new, introductory tutorials for the guide, and other activities that are part of an effort to expand and revise the guide. [See this thread from the distutils-sig](https://mail.python.org/pipermail/distutils-sig/2015-November/027776.html) for more details about this project. Work on these tutorials will (at least initially) take place on the `develop` branch.
> 
> I am inviting the group of volunteers to use this issue to see what other issues are available and to use this as a place for general questions and help (i.e., questions that are not issue-specific), to minimize noise on other issues and the creation of new issues.
> 
> If you'd like to contribute to these sections, please see the (to be) linked issues for details. Additionally, please review the [developing guide to contributing](https://packaging.python.org/contribute/). If you start work on an issue, please consider saying so on the relevant issue, so others don't duplicate your work. Thanks!
> 
> ## Outline
> Broadly, the new intro to packaging tutorials have the following outline:
> 
> 1. [Who is this for?](https://github.com/pypa/python-packaging-user-guide/issues/195)
> 2. [Prerequisites](https://github.com/pypa/python-packaging-user-guide/issues/196)
> 3. [What's a package?](https://github.com/pypa/python-packaging-user-guide/issues/199)
> 4. [Where do packages come from?](https://github.com/pypa/python-packaging-user-guide/issues/200)
> 5. [Install your first package](https://github.com/pypa/python-packaging-user-guide/issues/201)
> 6. [Use a virtual environment](https://github.com/pypa/python-packaging-user-guide/issues/202)
> 7. [Make your first package](https://github.com/pypa/python-packaging-user-guide/issues/203)
> 8. [Publish your first package](https://github.com/pypa/python-packaging-user-guide/issues/204)
> 
> Issues will soon be created to address each section specifically; the outline above will link to each section's issue.
> 
> ## Bite size tasks
> * [Add build instructions to the README #207](https://github.com/pypa/packaging.python.org/issues/207): Add build instructions to the README
> 
> ## Extra style notes
> The intro to packaging tutorials have some extra style considerations on top of that of the guide generally:
> 
> * In contrast to more task-focused writing, the tutorials are meant to build fundamental packaging skills, rather than resolve a specific problem. With that in mind, try to invite readers to learn to do something without regard for its specific applications. So instead of something like "Read this section if you want to share a package…" try "After you complete this section, you'll be able to share a package…"

**Comment by pradyunsg** [comment]
Looks like bots have decided that this is a good issue to spam. A different maintainer locked this to avoid more spam being spewed here.
