### ISSUE TITLE
New tutorials: publish a package

### ISSUE THREAD

**Issue by ddbeck** [pypa/packaging.python.org#204]
(For more information about this issue, please see #194).

We need a short section to follow the section about making a package (see #203) (i.e., as its own file). It should satisfy the following goals:
- show how to register with PyPI/testPyPI
- ask the reader to install twine (by this point they should be pretty comfortable installing things!)
- demonstrate uploading an sdist and wheel with twine (initial version)
- demonstrate uploading an sdist and wheel with twine (second version)
- admire your handiwork on the web

**Important note**: aside from registration, have the reader use testPyPI to learn the steps in this section.

It's OK to assume that the reader completed the previous section successfully and has a package that they can use with testPyPI.

When opening pull requests for this issue, please submit to the `develop` branch. If you have questions that concern contributing more generally, please use issue #194. Otherwise, feel free to comment with questions or feedback. Thanks!

**Comment by souravsingh** [comment]
@ddbeck I will be working on this

**Comment by jeanas** [comment]
This has long existed ([Packaging Python projects](https://packaging.python.org/en/latest/tutorials/packaging-projects/)).
