### ISSUE TITLE
Idea: Provide a list of known Python 3 backport projects?

### ISSUE THREAD

**Issue by ncoghlan** [pypa/packaging.python.org#209]
After seeing a link to https://github.com/google/python-subprocess32 on Twitter (which was a new discovery even for me), it occurred to me to wonder if we might be able to do better than https://wiki.python.org/moin/Python2orPython3#Supporting_Python_2_and_Python_3_in_a_common_code_base for maintaining a list of backport projects that make Python 3 features available to Python 2.7 users.

I'm not sure a PyPUG advanced topic is the right solution to this, but my reasons for suggesting it are:
- the user experience for editing PyPUG is smoother than that for editing the MoinMoin wiki (due to the use of both GitHub PRs for updates and ReStructured Text for markup)
- there's a pre-publication review step from the PyPUG maintainers
- it separates the resource list of backported modules from the more advisory aspects of the "Python 2 or 3?" wiki page
- it will hopefully help to build awareness of packaging.python.org more generally as a community resource (since the new page would be useful even to community veterans)

**Comment by berkerpeksag** [comment]
+1

There's also https://wiki.python.org/moin/StandardLibraryBackports for listing stdlib backports.

**Comment by hugovk** [comment]
This is probably no longer necessary now we're one year after the Python 2 EOL. Close this issue?
