### ISSUE TITLE
appveyor.yml unnecessarily complicated

### ISSUE THREAD

**Issue by AvdN** [pypa/packaging.python.org#221]
In the appveyor.yml file there double quoted lines which require backslashes to be escaped. This makes the files unnecessarily complicated and above all this is not consistently applied E.g (gathered from multiple lines in the file).

```
   - PYTHON: "C:\\Python27-x64"
   - "build.cmd %PYTHON%\\python.exe setup.py bdist_wheel"
   - path: dist\*
```

YAML supports both single quotes and unquoted strings with spaces, neither of which require backslashes to be escaped. So you can more naturally do :

```
    - PYTHON: 'C:\\Python27-x64'
    - 'build.cmd %PYTHON%\python.exe setup.py bdist_wheel'
```

or

```
    - PYTHON: C:\\Python27-x64
    - build.cmd %PYTHON%\python.exe setup.py bdist_wheel
```

The example should be updated to consistently use simpler YAML syntax used for the artifact path specification. The alternative would be to consistently use single quotes. 
Should I make a PR for either of those?

**Comment by jayvdb** [comment]
Hi @AvdN , it would be great if you can contribute this issue description and the fix to https://github.com/ogrisel/python-appveyor-demo first , as that project has CI using the sample `appveyor.yml` to verify it does work as expected.  Then copy & paste here ;-)
