### ISSUE TITLE
Add scikit-build to the list of non-PyPA projects of interest

### ISSUE THREAD

**Issue by ncoghlan** [pypa/packaging.python.org#381]
As enscons is to Scons, scikit-build is to CMake (they even release a pip installable CMake build to make that possible).

Docs: https://scikit-build.readthedocs.io/

(Discovered while researching my options for making the libsolv Python bindings pip installable)

**Comment by nathanielcompton** [comment]
@di Saw that you took over packaging, and tagging you here. We should be able to close this issue as https://github.com/pypa/packaging.python.org/pull/530 resolved it.

As I get more free time, I'll try to find more close-able issues in this repo 👍

**Comment by pradyunsg** [comment]
Thanks @nathanielcompton!
