### ISSUE TITLE
Guide and/or tutorial for command execution tools

### ISSUE THREAD

**Issue by ncoghlan** [pypa/packaging.python.org#406]
Once you've bootstrapped yourself a generally available Python installation, it's useful to be able to run Python scripts without having to explicitly set up virtual environments for them, without having to globally install all of their dependencies, and without having to rely on platform specific package management tools.

* `pipsi` handles that for fully packages projects: https://pypi.python.org/pypi/pipsi/
* `fades` handles it for unpackaged single file scripts: https://pypi.python.org/pypi/fades/

**Comment by untitaker** [comment]
I'd like something like that to be included in pipenv similar to how cargo does it.

**Comment by ncoghlan** [comment]
At least for now, this is considered out of scope for `pipenv`, since it manages ephemeral environments, while user commands need persistent ones: https://github.com/pypa/pipenv/issues/609

**Comment by uranusjr** [comment]
For Pipenv there is at least a workaround. Some packages are impossible to install with pipsi because of this constraint, e.g. `pipsi install jupyter`.

**Comment by willsALMANJ** [comment]
Another project like `pipsi` is `pipx`: https://github.com/cs01/pipx It is very new at the moment but worth keeping an eye on.

**Comment by cs01** [comment]
> Some packages are impossible to install with pipsi because of this constraint, e.g. `pipsi install jupyter`.

In case anyone is interested, I just added this feature to pipx. 

The `--include-deps` flag will recursively search all packages for entry points and expose them on the user's PATH.

```
> pipx install jupyter --include-deps
  These binaries are now globally available
    - iptest
    - iptest3
    - ipython
    - ipython3
    - jsonschema
    - jupyter
    - jupyter-bundlerextension
    - jupyter-console
    - jupyter-kernel
    - jupyter-kernelspec
    - jupyter-migrate
    - jupyter-nbconvert
    - jupyter-nbextension
    - jupyter-notebook
    - jupyter-qtconsole
    - jupyter-run
    - jupyter-serverextension
    - jupyter-troubleshoot
    - jupyter-trust
done! ✨ 🌟 ✨
```

**Comment by theacodes** [comment]
Now that we have a pipx guide, does it make sense to close this? I'm happy to see a pipsi guide as well, but I'm unsure if we need to leave this open.

**Comment by ncoghlan** [comment]
Yep, the new `pipx` guide covers this. Thanks @cs01!
