### ISSUE TITLE
tutorials/installing-packages is problematic in the way it deals with multiples operating systems.

### ISSUE THREAD

**Issue by sffjunkie** [pypa/packaging.python.org#453]
The installing packages page has the following note

*"Due to the way most Linux distributions are handling the Python 3 migration, Linux users using the system Python without creating a virtual environment first should replace the python command in this tutorial with python3"*

However most of the commands are already changed to `python3` in the rest of the text. Therefore on Windows when following the tutorial the command `python3` is not found because it does not exist.

**Comment by ncoghlan** [comment]
The instructions that start with `python3` relating to creating virtual environments, which typically isn't needed on non-Linux systems.

It's definitely a problem with trying to handle Linux and Mac OS X in the same guide as we use to handle Windows, though - the baseline starting states for the 3 operating systems are *very* different, so we end up with cases like this where it isn't obvious that folks on Windows are likely better off not worrying about virtual environments when they're just getting started :(

(See also https://github.com/pypa/python-packaging-user-guide/issues/393 and https://github.com/pypa/python-packaging-user-guide/issues/396)

**Comment by jeanas** [comment]
This should be fine now. The [guide](https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/) in question has “Unix/macOS” and “Windows” tabs, with `python3` only in the former.
