### ISSUE TITLE
Update pypi.python.org links to pypi.org links

### ISSUE THREAD

**Issue by brainwane** [pypa/packaging.python.org#476]
I think this would be a pretty easy task for a new first-timer.

1. Follow `README.rst` to clone and build the guide locally.

2. In the root of the repository, run:

`git grep "https://pypi.python.org"`

3. Go through those files and replace most of the old pypi.python.org URLs with new pypi.org URLs. Guides: https://packaging.python.org/guides/migrating-to-pypi-org/ and https://warehouse.readthedocs.io/api-reference/integration-guide/#migrating-to-the-new-pypi . If you want to, get fancy with regular expressions -- http://regexr.com/ might help. Be careful not to change URLs where we deliberately mean to mention the deprecated old address.

4. In the root of the repository, build the guide. Verify that all the links you changed work.

5. Submit PR. :)

**Comment by pgadige** [comment]
I'm working on this
