### ISSUE TITLE
Catalog of bdist_{rpm, deb, nsi, wininst, msi, esky, wheel} utilities?

### ISSUE THREAD

**Issue by westurner** [pypa/packaging.python.org#48]
There are myriad ways to generate OS packages and installers from setuptools. The question has been presented a number of times. Would a separate page for cataloging bdist_\* methods be in scope for this project?
- http://www.reddit.com/r/Python/comments/1qx2nb/distributing_python_3_applications_very_tempted/cdhnwku
- http://www.reddit.com/r/Python/comments/1ew4l5/im_giving_a_demo_of_python_to_a_bunch_of_java/ca4gf55

**Comment by hugovk** [comment]
By now, I think all of these, except wheel, are either removed, deprecated or at least discouraged.

Here's a discussion from this weekend with (so far) agreement on removing bdist_wheel. 

https://discuss.python.org/t/remove-bdist-wininst-command/6434?u=hugovk

See also:

* https://www.python.org/dev/peps/pep-0527/ 
* https://github.com/pypa/warehouse/issues/6792
* https://github.com/pypa/setuptools/issues/1988 

Anyway, I think this issue can be closed now.
