### ISSUE TITLE
How to do Documentation is missing.

### ISSUE THREAD

**Issue by illume** [pypa/packaging.python.org#484]
- How to upload documentation is important for packages.
- Which documentation tool to use (Sphinx)

**Comment by elainechan** [comment]
Working on this

**Comment by elainechan** [comment]
Made pull request https://github.com/pypa/python-packaging-user-guide/pull/568

**Comment by rffontenelle** [comment]
PR landed, is there anything left to do in this issue?

**Comment by illume** [comment]
The items originally listed in this issue are covered.

However more could be done.
https://github.com/pypa/packaging.python.org/pull/568#issuecomment-465095146

That’s a comment which was not answered on the PR. It suggests writing how to include docs in the sdist/whl. Which is definitely useful IMHO.

Should README.md docs be addressed as light weight alternative? Probably. Along with some guidance on some benefits of putting in the extra effort with Sphinx.

Examples are an important pillar of documentation, and that also could be addressed. Is there an examples/ folder, do you render the examples from there or include them in doc strings with doc tests? Do you include the examples in the package so people can more easily run them?

Probably even telling people there exists different types of documentation could be useful. Probably there are good resources we could link to?

There’s quite a confusion around how to document argument parameters in python. Types for documentation is another topic which is useful. Having a recommended way to do these would help a lot of people. I mean, probably today you wouldn’t choose numpy style with the types written in doc strings.

Not sure where you draw the line about what should go into guide on packaging. Maybe only topics related to packaging and distributing documentation?

**Comment by illume** [comment]
Maybe this issue can be closed, and further more specific issues can be made?

**Comment by webknjaz** [comment]
Sounds reasonable. A new issue is optional.
