### ISSUE TITLE
Packaging Tutorial should mention that packages TestPyPI and PyPI are different sets

### ISSUE THREAD

**Issue by pradyunsg** [pypa/packaging.python.org#528]
From https://github.com/pypa/packaging-problems/issues/170

Packages on TestPyPI and PyPI can differ. This can result in a hard-to-debug issue where one is unable to install `my-package` as `dependency` is not available on TestPyPI. It's not clear to a first timer that this might happen and what they should do next, since doing `pip install dependency` would work out for them but the suggested way to test their TestPyPI package won't.

I think there's 2 possible suggestions here:

- Using `--no-deps` to install the `my-package` and then doing `pip install my-package` to install `dependency` from PyPI.
- Making the user manually install `dependency` from PyPI then installing `my-package` from TestPyPI.

I'd prefer the former since there's no need to manually mention the dependencies (assuming it works; I didn't check).

**Comment by dstufft** [comment]
This is probably covered long term by https://github.com/pypa/warehouse/issues/2286, https://github.com/pypa/warehouse/issues/918, or https://github.com/pypa/warehouse/issues/726.

**Comment by pastelmind** [comment]
I think this overlaps with #559, which was closed by #593. Should this be closed?
