### ISSUE TITLE
Some links in search results are 404

### ISSUE THREAD

**Issue by di** [pypa/packaging.python.org#567]
For example, the second link currently at:

https://packaging.python.org/search/?q=distribution&check_keywords=yes&area=default

is: 

http://packaging.python.org/specifications/index?highlight=distribution

However this link 404's, as the page is actually at:

https://packaging.python.org/specifications/

**Comment by ncoghlan** [comment]
Adding the file extension also results in a correct link: https://packaging.python.org/specifications/index.html?highlight=distribution

Is it possible we're hitting a Sphinx HtmlDir bug?

**Comment by ncoghlan** [comment]
I didn't find anything recent, but https://github.com/sphinx-doc/sphinx/issues/3696 and https://github.com/sphinx-doc/sphinx/issues/3696 suggest that this *is* an area where there's some potential fragility in the link generation.

**Comment by pradyunsg** [comment]
I just got directed to https://packaging.python.org/search/guides/tool-recommendations/?highlight=recommend from a search for "recommend" just now.

Not sure if it's the exact same issue but it's search-related.

**Comment by di** [comment]
Seems like the same issue to me.

**Comment by pradyunsg** [comment]
Looking at https://docs.readthedocs.io/en/latest/team.html#support-team, @ericholscher perhaps?

**Comment by Frame42** [comment]
in https://packaging.python.org/tutorials/packaging-projects/ 
link https://test.pypi.org/project/example-pkg-your-username gives a 404

**Comment by webknjaz** [comment]
@di @pradyunsg do you know if this is still unresolved?

@Frame42
> in [packaging.python.org/tutorials/packaging-projects](https://packaging.python.org/tutorials/packaging-projects/)
> link [test.pypi.org/project/example-pkg-your-username](https://test.pypi.org/project/example-pkg-your-username) gives a 404

That is a template link, it's not supposed to lead anywhere

**Comment by di** [comment]
I haven't seen this recently, I think it can probably be closed.

**Comment by webknjaz** [comment]
Yeah, looks like nobody's added any new reports for the last 3 years. We can reopen later.
