### ISSUE TITLE
Mention find_namespace_package function in "Packaging namespace packages" guide.

### ISSUE THREAD

**Issue by feluxe** [pypa/packaging.python.org#580]
I was struggling with a namespace packge for a long time until I found out about `setuptools.find_namespace_packages()` in a github issue.

I think it would be nice if `find_namespace_packages()` was mentioned in this guide:

https://packaging.python.org/guides/packaging-namespace-packages/#packaging-namespace-packages

There is this section already:

> Because mynamespace doesn’t contain an __init__.py, setuptools.find_packages() won’t find the sub-package. You must explicitly list all packages in your setup.py. For example:

I think it would be nice if it was updated to something like this:

> Because mynamespace doesn’t contain an __init__.py, setuptools.find_packages() won’t find the sub-package. To get the sub-packages, you must either use setuptools.find_namespace_packages() or explicitly list all sub-packages in your setup.py. For example:

**Comment by theacodes** [comment]
Thanks for reporting this! This is a great first issue for someone. :)

**Comment by plemelin** [comment]
@theacodes 
I stumble upon this issue. After reading https://github.com/pypa/setuptools/issues/97 I could not find any reference to `find_namespace_packages` other than the code itself. Hopefully the text suits the needs

**Comment by avaldebe** [comment]
It looks to me that this issue was addressed on #622, so you should be able to close it.
