### ISSUE TITLE
Rename this project to packaging.python.org

### ISSUE THREAD

**Issue by theacodes** [pypa/packaging.python.org#590]
It's actually super confusing that this project's name on github doesn't match the serving domain name, so I'd like to go ahead and rename this to `pypa/packaging.python.org` unless anyone has any concerns.

@ncoghlan can you handle this as a PyPA admin?

**Comment by pradyunsg** [comment]
> I'd like to go ahead and rename this to `pypa/packaging.python.org`

Completely on board for this.

> unless anyone has any concerns

Travis CI and RTD will need updates for their references?

> can you handle this as a PyPA admin?

I don't think @ncoghlan has the PyPA admin bit: https://github.com/orgs/pypa/people?utf8=%E2%9C%93&query=+role%3Aowner

**Comment by ncoghlan** [comment]
Yeah, I've usually bugged @dstufft when I needed admin level stuff done (I think @pfmoore may have admin as well).

+1 for renaming, though - the only reason they don't already match is because we didn't actually have the domain name assigned when the project started and the affiliation with the PSF was loose enough that it wasn't clear if/when we'd get it.

**Comment by pfmoore** [comment]
I have the ability to rename, but I have absolutely no feel for what the impact of doing so would be. For example, wouldn't it break users' email filters that put notifications from this repo into a specific folder?

I'm willing to push the button if the consensus is that it should be done - but I'm not willing to take the flak for doing so :wink:. And personally I think the risks outweigh the benefits.

**Comment by pradyunsg** [comment]
> https://github.com/orgs/pypa/people?utf8=%E2%9C%93&query=+role%3Aowner

FWIW, anyone listed here can make the rename happen.

> For example, wouldn't it break users' email filters that put notifications from this repo into a specific folder?

I think so.

**Comment by theacodes** [comment]
Email filters might break. Travis accommodates renames well. I *think* ReadTheDocs will be fine, but if not, I'm an admin there and can fix it.

**Comment by pfmoore** [comment]
Issue links from other projects and/or external pages? Does github maintain redirects when a project gets renamed?

**Comment by pradyunsg** [comment]
> Travis accommodates renames well. I think ReadTheDocs will be fine, but if not, I'm an admin there and can fix it.

I have no more concerns -- let's do this.

**Comment by theacodes** [comment]
@di or @pfmoore, let's do this pretty please?

**Comment by pfmoore** [comment]
OK, I'll do this now. Posting this *before* I do it so that if any emails go astray post-rename, at least people will have seen this :-)

**Comment by pfmoore** [comment]
Oh, and note that anything around Travis and/or RTD, I don't have the means to do (it's possible I have permissions, but I've no idea how to). All I'm going to do is rename the github project. Hope that's what is expected.

**Comment by pfmoore** [comment]
Done. And I got here by following the link from an email sent prior to the rename, so it looks like redirects are working :-)

**Comment by pradyunsg** [comment]
Awesome! Thanks @pfmoore!

**Comment by ncoghlan** [comment]
ReadTheDocs project admins are me, Thea, Donald, and Marcus. (Has anyone heard from Marcus lately and know what he is up to these days?)

**Comment by ncoghlan** [comment]
I've updated what can be updated on https://readthedocs.org/projects/python-packaging-user-guide/ so it isn't reliant on the GitHub redirect any more. Perhaps we should add a link to the GitHub README so future maintainers are made aware of where the RTD config actually lives, and who currently has access?

**Comment by theacodes** [comment]
Yay, thanks, all!

> Perhaps we should add a link to the GitHub README so future maintainers are made aware of where the RTD config actually lives, and who currently has access?

@ncoghlan https://github.com/pypa/packaging.python.org/pull/600
