### ISSUE TITLE
Platform related issue after packaging with 2 different command.

### ISSUE THREAD

**Issue by akshaykanawat** [pypa/packaging.python.org#598]
I've built a private python package which I hosted on bitbucket using "python setup.py bdist_wheel" command and after some modifications, I again rebuilt the package using "python setup.py sdist" command by mistake, which is for source distribution. After that in dist folder two archived files created, one with .gz format and the other with .whl format. Now when I am installing the package, modifications in the file are coming in ubuntu os, but when I am installing it on mac os, those modifications are not coming. I wanted to know that why this is happening?

**Comment by jwodder** [comment]
What version of pip do you have on Ubuntu and Mac OS?

**Comment by akshaykanawat** [comment]
> What version of pip do you have on Ubuntu and Mac OS?

For ubuntu it is pip 8.1.1 and for mac it was 2.7

**Comment by merwok** [comment]
> Now when I am installing the package, modifications in the file are coming in ubuntu os

What exact command are you using to install the package?
How exactly do you see that modifications are coming?
