### ISSUE TITLE
Repeated word "audience" in overview

### ISSUE THREAD

**Issue by guy881** [pypa/packaging.python.org#603]
Hey, I probably found a mistake on this page: https://packaging.python.org/overview/#id9

> Based on our introduction, you would be correct to infer these built-in approaches only target environments which have Python, and an **audience audience** who knows how to install Python packages.

I am not a native speaker, but I suppose this is just a unintended repetition of word  "audience".

**Comment by theacodes** [comment]
Thanks, @guy881!
