### ISSUE TITLE
Incorrect Wording in Docs

### ISSUE THREAD

**Issue by jakenorth** [pypa/packaging.python.org#638]
Small wording error on this page:
https://packaging.python.org/guides/analyzing-pypi-package-downloads/

> A number of things prevent the download counts from being inaccurate, some of which include: [proceeds to list things that make download counts inaccurate and unreliable]

This should say "prevent the download counts from being **accurate**" instead of "prevent the download counts from being **inaccurate**"

**Comment by di** [comment]
Closed in #639.
