### ISSUE TITLE
Website not updating

### ISSUE THREAD

**Issue by jwodder** [pypa/packaging.python.org#640]
Even though the repository was last committed to on August 13, the date at the bottom of https://packaging.python.org says that the site hasn't been updated since April 23 — and, indeed, the pull requests merged since then don't appear to have been applied to the site.

**Comment by pradyunsg** [comment]
Seems to me that RTD isn't getting the relevant events from GitHub.

https://readthedocs.org/projects/python-packaging-user-guide/builds/

**Comment by di** [comment]
The webhook is failing and it's not clear to me why. I filed https://github.com/readthedocs/readthedocs.org/issues/6122.

**Comment by di** [comment]
OK, this should be resolved, [the most recent build](https://readthedocs.org/projects/python-packaging-user-guide/builds/9584920/) was automatically triggered from https://github.com/pypa/packaging.python.org/commit/fb64a4d9645744aec4faa35a5b07138f4ea8f386.
