### ISSUE TITLE
Document the "Do not upload" classifier trick

### ISSUE THREAD

**Issue by pganssle** [pypa/packaging.python.org#643]
In [this tweet](https://twitter.com/di_codes/status/1097220464445931525), @di mentions a trick to prevent accidentally uploading your packages to PyPI by adding a `Private :: Do Not Upload` classifier and in the thread @ewdurbin mentioned that he had made `Private` a reserved top-level classifier so the trick works reliably.

It seems like it would be a good idea to document this somewhere for easy linking. It could go into a tutorial or maybe we can add a "miscellaneous tips and tricks" section?

**Comment by Julian** [comment]
Should there be a `License :: Closed Source` for this? Having two ways to do it isn't great obviously, but possibly the advantage of using License is some tools maybe care about being able to ask about the license anyhow from classifiers, so maybe using that namespace solves both?

**Comment by pfmoore** [comment]
I may well have an open source project that I don't want to upload to PyPI (maybe because it's not yet ready for broad distribution).

**Comment by imankulov** [comment]
I came across this issue while finding a way to mark my python packages as private. Adding a cross-reference to a change in Warehouse which sort of "institutionalizes the trick": https://github.com/pypa/warehouse/pull/5440

**Comment by hugovk** [comment]
> [https://github.com/pypa/warehouse/blob/master/warehouse/templates/pages/classifiers.html](https://github.com/pypa/warehouse/blob/master/warehouse/templates/pages/classifiers.html?rgh-link-date=2019-08-27T15%3A09%3A25Z) which renders [pypi.org/classifiers](https://pypi.org/classifiers/) could probably also address this.

Please see PR https://github.com/pypa/warehouse/pull/10872 to document it on that page.

Is that sufficient or is something also needed on https://packaging.python.org?

**Comment by hugovk** [comment]
> Is that sufficient or is something also needed on [packaging.python.org](https://packaging.python.org)?

Please see https://github.com/pypa/packaging.python.org/pull/1056 as well :)
