### ISSUE TITLE
request for clarification in packaging tutorial: graduating to canonical PyPI

### ISSUE THREAD

**Issue by brainwane** [pypa/packaging.python.org#653]
At [a recent sprint night](https://www.meetup.com/nycpython/events/265028634/) a new user asked: in the "Next steps", once I'm ready to upload to pypi.org instead of Test PyPI. what's the new PyPI URL I should upload to?

There's a section starting:

>When you are ready to upload a real package to the Python Package Index you can do much the same as you did in this tutorial, but with these important differences:

but it doesn't tell the user what the new upload URL will be.

**Comment by bsolomon1124** [comment]
I believe this value is specified at `twine/utils.py` as

```python
DEFAULT_REPOSITORY = "https://upload.pypi.org/legacy/"
```

However, in the interest of not introducing possible link rot, maybe it would suffice to just say something like, "`twine upload` defaults to the "real" pypi.org, so you don't need to specify `--repository-url` in this case."
