### ISSUE TITLE
Python 3.8.0 and Pip3 install fails: matplotlib, opencv-python, speech_recognition and many more..

### ISSUE THREAD

**Issue by DrGurkan** [pypa/packaging.python.org#662]
Hi,

I've encountered many pip3 install fails after I've migrated to Pyhton version 3.8.0 (I am using windows 10), my pip3 is up to date (as mentioned as a problem somewhere). I guess you are aware of this problem, if yes then when we will be able to use those packages on python 3.8.0?
Here are a few of these fails:
pip3 install speech_recognition
ERROR: Could not find a version that satisfies the requirement speech_recognition (from versions: none)
ERROR: No matching distribution found for speech_recognition
-------------
pip3 install opencv-python
ERROR: Could not find a version that satisfies the requirement opencv-python (from versions: none)
ERROR: No matching distribution found for opencv-python
--------------
pip3 install matplotlib
Installing collected packages: cycler, kiwisolver, pyparsing, python-dateutil, matplotlib
    Running setup.py install for kiwisolver ... error
    ERROR: Command errored out with exit status 1:
--------------

**Comment by webknjaz** [comment]
@DrGurkan this resource contains generic information about packaging. You have to ask those project maintainers directly. Nobody here will be able to help you.

**Comment by ncoghlan** [comment]
Python 3.8 is still relatively new, and it often takes a while for projects to start publishing binaries for the new release (especially volunteer-maintained projects where folks need to find time to run the extra builds).

If you have complex binary dependencies (and from your examples, it appears you do), then it's often a good idea to wait for the X.Y.1 release before updating.

If you're looking for more info in the meantime, then the specific projects involved may have that available.
