### ISSUE TITLE
Dead link to "table schema"

### ISSUE THREAD

**Issue by jugmac00** [pypa/packaging.python.org#664]
On the page
https://packaging.python.org/guides/analyzing-pypi-package-downloads/
the link behind "table schema"
points to the url
`https://bigquery.cloud.google.com/table/the-psf:pypi.downloads20161022?tab=schema`
which does not work anymore.

https://github.com/pypa/packaging.python.org/blame/master/source/guides/analyzing-pypi-package-downloads.rst#L58

**Comment by di** [comment]
The link works for me:

<img width="846" alt="Screen Shot 2019-10-28 at 2 19 54 PM" src="https://user-images.githubusercontent.com/294415/67710504-1422ad80-f98e-11e9-8196-2506933ff624.png">

What makes you think it's dead?

**Comment by di** [comment]
(As an aside, it looks like this UI will be going away next year, and we should update the link to something like https://console.cloud.google.com/bigquery?pli=1&p=the-psf&d=pypi&t=downloads&page=table instead.)

**Comment by jugmac00** [comment]
Hi @di 
thanks for the quick response and sorry for not attaching a screenshot.

I get a "Unable to find table: the-psf:pypi.downloads20161022 " message.

For me it looks like on the attached screenshot - I tried both Chrome and Firefox on Ubuntu 18.04.

As I have to login with my Google account, maybe it is an authorization issue? From the text at the documentation I assumed it is viewable by everybody.

![Screenshot from 2019-10-28 20-43-40](https://user-images.githubusercontent.com/9895620/67712552-7e564500-f9c4-11e9-839b-a96d1ffd1ee0.png)

**Comment by di** [comment]
Hmm, does https://bigquery.cloud.google.com/dataset/the-psf:pypi load for you?

This is a public dataset, so it should be available to everyone.

**Comment by jugmac00** [comment]
Same problem :-(

The page starts loading - a small popup appears for login to the Google account. After that the situation on the screenshot appears.

![Screenshot from 2019-10-28 21-35-31](https://user-images.githubusercontent.com/9895620/67715860-edcf3300-f9ca-11e9-8b03-e2008a0a566f.png)

**Comment by jugmac00** [comment]
Update... I made it work. Well, I guess 25+ years of www experience is hardly enough to handle the Google BigQuery gui...

Had to open a second browser window and head directly to https://bigquery.cloud.google.com/

On the next screen I had to click on "existing project"

![Screenshot from 2019-10-28 21-44-48](https://user-images.githubusercontent.com/9895620/67716988-24a64880-f9cd-11e9-9e53-dbc5d3a2c59f.png)

Next, I had to create a dummy project....

And... magically in the first browser window now I was able to see the psf data... Well, if everything would be that easy....

@di Sorry for bothering you!

**Comment by fhoffa** [comment]
I don't see a problem, but if you have problems - try the new UI:

- https://console.cloud.google.com/bigquery?p=the-psf&d=pypi&t=downloads20191028&page=table

Does it load?


To save a lot on querying costs, try using my tables instead:

- https://towardsdatascience.com/python-pypi-stats-in-bigquery-reclustered-d80e583e1bfe

(hopefully we can do this in the master datasets, but you can use my tables for now)


For example, this query goes over 0.37 GB vs 60.7 GB on the original:

```
SELECT REGEXP_EXTRACT(details.python, r'^\d*\.\d*') python
  , COUNT(*) downloads
FROM `fh-bigquery.pypi.pypi_2019`
WHERE project='pyspark'
AND timestamp>'2019-09-30' 
GROUP BY python
ORDER BY downloads DESC
# 3.3s elapsed, 373 MB processed
```

  
```
SELECT REGEXP_EXTRACT(details.python, r'^\d*\.\d*') python
  , COUNT(*) downloads
FROM `the-psf.pypi.downloads*`
WHERE file.project='pyspark'
AND _table_suffix>='20190930' 
GROUP BY python
ORDER BY downloads DESC
# 11.2s elapsed, 60.7 GB processed


```

**Comment by di** [comment]
@jugmac00 Ah, glad you figured it out. Sorry that's not very intuitive, we should probably add a note that this might happen if you haven't used BigQuery before, so I'll leave this issue open.

**Comment by jugmac00** [comment]
@fhoffa Thank you very much for your offer. I just had a discussion on Twitter about project download numbers which seems way to high - at least compared to human users.

I was pointed to https://packaging.python.org/guides/analyzing-pypi-package-downloads/ and I just was curios what kind of data is stored. I just wanted to see the column names - I am not interested int he data itself or using BigQuery.

As I found a "obviously" dead link I just wanted to report it.

Sorry again for the buzz and thanks again for being so nice and helpful!
