### ISSUE TITLE
Update Packaging Python Projects tutorial to use PEP 518

### ISSUE THREAD

**Issue by uranusjr** [pypa/packaging.python.org#693]
Currently the tutorial instructs the user to construct the package without `pyproject.toml`. A package built as such however has some install-time perculirities that may confuse users (see pypa/pip#7709 pypa/pip#7716). Adding `pyproject.toml` into the initial tutorial would help nudge the user onto the right track from the beginning. It could also be helpful for driving PEP 518 adoption—or at least not hampering it by introducing more new non-PEP 518 packages.

**Comment by bhrutledge** [comment]
With the resolution of #809, the tutorial now includes a minimal `pyproject.toml` to use `setuptools`. Can this be closed?

Also, is this is a duplicate of #720?

**Comment by uranusjr** [comment]
Yeah, I think #809 covers this. The *Packaging and distributing projects* guide could also use an update, but that's a separate issue.
