### ISSUE TITLE
Add Flit rationale to key projects entry

### ISSUE THREAD

**Issue by brainwane** [pypa/packaging.python.org#702]
This is a good first issue for someone: add a link to https://flit.readthedocs.io/en/latest/rationale.html within https://packaging.python.org/key_projects/#flit .

https://github.com/pypa/packaging.python.org/blob/master/source/key_projects.rst#flit is the file you would edit to do this. Perhaps the wording could be like:

> Flit is a simple way to put Python packages and modules on PyPI ([the maintainer's rationale for the tool](https://flit.readthedocs.io/en/latest/rationale.html)).

cc @takluyver

**Comment by pastelmind** [comment]
Please check out my attempt at #710.
