### ISSUE TITLE
Organize guides into categories

### ISSUE THREAD

**Issue by pastelmind** [pypa/packaging.python.org#709]
Currently, the [Guides index](https://packaging.python.org/guides/) contains a single huge list of 22 guides. This makes finding the right topic cumbersome. Organizing this list into categories would greatly improve readability and navigability.

(We do have a Search Box, but having a well-organized navbar is still important.)

Deciding *how* to categorize each guide may be subject to debate. We can start with simple, general categories and bikeshed later. I suggest using three broad categories:

- Installing Packages
    - Includes topics on installing tools as an end-user, or as dependencies.
- Building and Publishing Projects
    - Includes topics for configuring projects, creating sdists & wheels, publishing them online, and automating these tasks.
- Miscellaneous
    - Guides that do not clearly fit into any of the above

When the list of guides grows larger, we could add more categories.

I also created #708 as an example. However, I couldn't figure out how to create nested toctrees in the navbar. I'm not experienced in Sphinx; some help would be appreciated.

**Comment by webknjaz** [comment]
> I'm not experienced in Sphinx; some help would be appreciated.

There's
```rst
:maxdepth: 1
```
that essentially limits the TOC to the higher-level items. Changing it to `2` should include the subpages if that's what you're looking for. This relies on the file system structure, though.

**Comment by jeanas** [comment]
This was done in #708, and #1368 improved the sidebar.
