### ISSUE TITLE
Add "trove classifiers" project to key projects page

### ISSUE THREAD

**Issue by brainwane** [pypa/packaging.python.org#714]
This is a good first issue for someone: add an item within https://packaging.python.org/key_projects/#flit  about the `trove-classifiers` project https://github.com/pypa/trove-classifiers ([PyPI project](https://pypi.org/project/trove-classifiers/)).

https://github.com/pypa/packaging.python.org/blob/master/source/key_projects.rst is the file you would edit to do this. Copy the formatting of other PyPA project listings. The description could be like:

"Canonical source for [classifiers on PyPI](https://pypi.org/classifiers/), which project maintainers [use to systematically describe their projects](https://packaging.python.org/specifications/core-metadata/#classifier-multiple-use). Useful for validation checks."

**Comment by brainwane** [comment]
@arshadrr could you please try doing this?

Following up your successful work on https://github.com/pypa/warehouse/pull/8028 .

**Comment by arshadrr** [comment]
@brainwane I'll give it a go.
