### ISSUE TITLE
The "Packaging projects" tutorial should discuss using pyproject.toml

### ISSUE THREAD

**Issue by pfmoore** [pypa/packaging.python.org#720]
The tutorial at https://packaging.python.org/tutorials/packaging-projects/ describes building an old-style setuptools project. We should be covering using `pyproject.toml`. Reasons include:

1. It's the "modern" way of defining packages.
2. It ensures that the project defines its build dependency on `wheel`, which avoids oddities such as pip doing a direct `setup.py install` when installing from source.

See https://github.com/pypa/setuptools/issues/510#issuecomment-617031254 and https://github.com/pypa/pip/issues/8102 for context.

**Comment by bhrutledge** [comment]
With the resolution of #809, the tutorial now includes a minimal `pyproject.toml` to use `setuptools`. Can this be closed?
