### ISSUE TITLE
Update Key Projects links that point to pypa-dev Google Group

### ISSUE THREAD

**Issue by brainwane** [pypa/packaging.python.org#732]
We've now [decommissioned](https://groups.google.com/d/msg/pypa-dev/rUNsfIbruHM/LCEx-CB5AgAJ) the [pypa-dev Google Group](https://groups.google.com/forum/#!forum/pypa-dev).

I'd like for someone to go through [the Key Projects page](https://packaging.python.org/key_projects/) and update all the following "Dev list" links so that they point to [https://mail.python.org/mailman3/lists/distutils-sig.python.org/](https://mail.python.org/mailman3/lists/distutils-sig.python.org/) instead.

This is a good first contribution for someone who's new to this repository. You open up the file

 `key_projects.rst`

and change the URL on the following lines:

~~~
line 67:  `Dev list <http://groups.google.com/group/pypa-dev>`__ |
line 100: `Dev list <http://groups.google.com/group/pypa-dev>`__ |
line 184: `Dev list <http://groups.google.com/group/pypa-dev>`__ |
line 225: `Dev list <http://groups.google.com/group/pypa-dev>`__ |
~~~

and then open a pull request.

Followup to #731.

**Comment by frog-o** [comment]
In the  [decommissioned](https://groups.google.com/forum/#!msg/pypa-dev/rUNsfIbruHM/LCEx-CB5AgAJ)mailing list
it links to the reason for [close](https://groups.google.com/forum/#!msg/pypa-dev/twf9HCGfv3k/t2HJwzF-AgAJ)


>3. The Packaging category on Python's Discourse forum
https://discuss.python.org/c/packaging , which started about a year and
a half ago[3]. Very wide scope. You can log in with an account, or with
Facebook or GitHub or via email. About 21 posts per month. Hosted by PSF
with an open source application that's under active development.

Can some please explain how to login by github is done.
I want to post to this list but don't want The mailing list sent to my email.

**Comment by brainwane** [comment]
Moved the login question to a new issue.

**Comment by SaltyCatFish** [comment]
Just FYI

line 225: `Dev list <http://groups.google.com/group/pypa-dev>`__ | 

Actually 252.  Just for historical purposes.

Submitting pull request now.
