### ISSUE TITLE
Recommendation on the Packaging Projects Tutorial

### ISSUE THREAD

**Issue by DzRepo** [pypa/packaging.python.org#743]
Perhaps it's me, a total packaging noob, but when I went through the tutorial and came across
``` example_pkg/__init__.py is required to import the directory as a package, and can simply be an empty file.```
I created the empty file, and copied my module into the directory and left it at that.

Going through the rest of the exercise, I was surprised my module wasn't there when I installed into a new environment. Tracing backwards, I noticed that the file wasn't included in the tar.gz file. Some further research let me to the requirement of having an ```from  MyModule import *``` in the __init__.py 

I think having this tutorial written from the perspective of "I have a helloworld.py module" would be a bit easier to understand from a first-timer's point of view. From there, links on how to create / modify more sophisticated deployments would be the obvious next step.

Thanks for all the work you do in making Python developers' lives easier!

**Comment by merwok** [comment]
Hello!  I think there is some confusion here between _import modules_ and _distributable packages_, which I’ll try to clarify (maybe leading to a doc improvement).

Python imports modules.  A package is a special module made up of a directory that contains submodules, including a required special one in `__init__.py`.

To import a submodule, one needs to write `import example_pkg.sub_module` or `from example_pkg import sub_module`.

The packaging tooling is separate from the import system.  To package (meaning bundle or distribute) a Python package (here meaning a module with sub-modules) with setuptools, you typically need to have `setup(..., packages=["example_pkg"], ...)` in your `setup.py` script.

> Some further research let me to the requirement of having an `from MyModule import *` in the `__init__.py`

This is a personal preference, not something required by import or packaging systems!  It merely enables `import example_pkg` to have the same effect as `import example_pkg.sub_module`, which has pros and cons.

**Comment by bhrutledge** [comment]
As #913, the tutorial now includes an example module a function definition:

https://packaging.python.org/tutorials/packaging-projects/#a-simple-project

My hope is that's a sufficient minimal example. I think there's value in "following this tutorial as-is using this project, before packaging your own project", because it introduces the concepts in a concrete, reproducible way.

With that in mind, plus the age of this issue, could this be closed?

**Comment by webknjaz** [comment]
Sounds like it's solved.
