### ISSUE TITLE
Pipenv caveat: is it still valid?

### ISSUE THREAD

**Issue by alanfranz** [pypa/packaging.python.org#746]
Hello,
I'm about to start a new Python project, and I'd like to align to current Python good practices for packaging; I'm totally not a packaging newbie, but I've not used poetry/pipenv extensively (my current setup uses pip, setup.py and requirements.txt with custom Makefile targets).

So, I've come across this caveat:
https://packaging.python.org/tutorials/managing-dependencies/#recommendation-caveats-as-of-april-2020

But I see there have been two recent pipenv releases, one is from May, the other from June.

Is the caveat still valid? Should I use Pipenv?

**Comment by pradyunsg** [comment]
https://github.com/pypa/packaging.python.org/pull/729

We have a PR to remove the caveat. I'm waiting on another editor/expert to green-tick before merging. :)

**Comment by pradyunsg** [comment]
Removed by merging #729. Thanks for filing this issue @alanfranz! ^>^
