### ISSUE TITLE
Enable per-PR website previews

### ISSUE THREAD

**Issue by webknjaz** [pypa/packaging.python.org#762]
This is easy to do by connecting RTD and enabling PR builds: https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html.

Even though this website does not use RTD, it'd be beneficial to be able to see how the changes in PRs look.

**Comment by di** [comment]
Done!

**Comment by webknjaz** [comment]
@di it doesn't seem to be working: https://github.com/pypa/packaging.python.org/pull/763. Are you sure this repo has the right webhook integrated?

**Comment by di** [comment]
Looks like the webhook wasn't set to receive pull request notifications. It should be good now.
