### ISSUE TITLE
Packaging guide: please add a hint about avoiding "cannot import name from partially initialized module"

### ISSUE THREAD

**Issue by int-ua** [pypa/packaging.python.org#767]
https://packaging.python.org/tutorials/packaging-projects/ In the hindsight it's kind of obvious why it fails but when making a one-file project the straightforward solution is to name both directory and file with the same name. Adding a hint in that guide would improve UX as users will hopefully notice it before uploading and understanding that they can't do `from example_pkg import example_function` but instead have to either resort to  `from example_pkg.example_pkg import example_function` or go back and rename the file.

Example: 
https://gitlab.com/int-ua/inheritson/-/tree/52e4cddab8b9e46019c1aaf1fbc471dbb1356a25/inheritson

**Comment by int-ua** [comment]
fixed by `from .example_pkg import *` in the `__init__.py`

**Comment by webknjaz** [comment]
Hey Serhii, if you have a specific change in mind, feel free to send a pull request and we'll review it accordingly.
