### ISSUE TITLE
Redirect any `pep517` package porcelain commands references to `python-build`

### ISSUE THREAD

**Issue by webknjaz** [pypa/packaging.python.org#770]
We have to review all the repo contents for any recommendations to use `python -m pep517.build` or its variations. It's got popular because it was the only way to invoke PEP517 build backends while pip only has a CLI subcommand for building wheels but not sdists.
It is now being deprecated and the official recommendation is to point folks to [`python-build`](https://github.com/FFY00/python-build) instead. This project is in the progress of transitioning under PyPA but is already quite usable.

One place using `pep517.build` that I know of is https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/ but there may be more.

See the discussion @ https://github.com/pypa/pep517/pull/83 for more details.

**Comment by webknjaz** [comment]
cc @FFY00

**Comment by pfmoore** [comment]
Searching the repo, that's the only occurrence (from #647)

**Comment by henryiii** [comment]
This is closable now, fixed by pypa/setuptools#2519. #817 would update one of the setup.py builds with `python -m build`, as well.

**Comment by merwok** [comment]
Can I ask why the guide uses pep517/python-build and not pip?

If  I remember correctly, python-build is meant to be a reference implementation of an installer following PEP 517 and 518.  I am not using it myself because I use virtualenvs and pip.  Problem reports are starting to show up: https://github.com/pypa/packaging-problems/issues?q=is%3Aissue+is%3Aopen+%22python3+-m+build+%22

From the tracebacks, I see that python-build calls pip, so I find this situation unclear.

**Comment by FFY00** [comment]
pip cannot build sdists AFAIK. pypa/build calls pip when setting up an isolated environment to then build the packages, but the building step does not involve pip in any way, it is just the means to provision the environment. In fact, pypa/build using pip is just an implementation detail, it could change the way it provisions the isolated environments any time.

I hope that was clear, but if it wasn't please let me know.

**Comment by henryiii** [comment]
Pip is a package installer, not a package builder. There's no way to make an SDist through pip, as well. `pypa/build` does call pip to install packages. There's a bug in the tutorial that would be fixed by #823, but that's not merged yet.

**Comment by henryiii** [comment]
With the exception of the issue that was due to a bug in build 0.2.0 fixed in 0.2.1, those issues are not related to build, really, but issues (primarily with a missing line in the example that I'm trying to get fixed in #823 )

**Comment by merwok** [comment]
> Pip is a package installer, not a package builder.

Glad to hear that!  There wasn’t a general agreement about that for years.

> There's no way to make an SDist through pip, as well.

The future is here!
