### ISSUE TITLE
GitHub Actions tutorial: Warn about filling up test pypi package limit if you publish every commit as suggested 

### ISSUE THREAD

**Issue by bhazelton** [pypa/packaging.python.org#777]
I followed the guide at https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/ and got everything working so that every push to our main branch was published to test.pypi and only actual releases were published to pypi. We were very happy for several months until the push to test.pypi started erroring because we had hit the project size limit. I went to the package page on test.pypi and discovered (unsurprisingly in retrospect) hundreds of releases published on test.pypi that accumulated to put us at our package size limit.

As far as I can tell, there does not seem to be a way either to set time limits on these releases so they are auto-deleted or to batch delete them in any way. I had to go through a very laborious process of clicking on the options button for each unwanted release, selecting `Delete` and then copying the release name into the the verification box. Please add some text to the tutorial warning users of the potential ramifications of publishing every push to test.pypi, which is what is currently suggested in the tutorial. Or if there are better ways to auto-delete or otherwise manage such test releases, please add language explaining how to do better.

**Comment by webknjaz** [comment]
@di @pradyunsg could you please mark this as "good first issue" / "Hacktoberfest"?

**Comment by webknjaz** [comment]
If anyone is to submit the PR, I think it's worth using an "attention" box and pointing to https://pypi.org/help/#project-size-limit from the text.

**Comment by webknjaz** [comment]
Another thing such a warning could suggest is using a custom PyPI-compatible server in CI just for testing.
