### ISSUE TITLE
HTTPError: 403 Forbidden from https://test.pypi.org/legacy/

### ISSUE THREAD

**Issue by Duchongc** [pypa/packaging.python.org#779]
Run: python3 -m twine upload --repository testpypi dist/*

HTTPError: 403 Forbidden from https://test.pypi.org/legacy/
Invalid or non-existent authentication information. See https://test.pypi.org/help/#invalid-auth for more information.
What's the problem?

**Comment by webknjaz** [comment]
Your test.pypi.org username+password pair is invalid.

**Comment by lkiko** [comment]
ERROR    HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/
         Invalid or non-existent authentication information. See https://pypi.org/help/#invalid-auth for more information.
I still have this error after using the API. I am already depressed. Has anyone resolved it?
