### ISSUE TITLE
Small mistake in guide

### ISSUE THREAD

**Issue by NicMan30** [pypa/packaging.python.org#783]
I'm relatively new to programming so please forgive me if it really is correct, but I'm pretty sure that on https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/ in the section on _Activating a virtual environment_ the windows response to the command **where python** should be **...\env\Scripts\python.exe** instead of **.../env/bin/python.exe**. At least it is for me.

**Comment by henryiii** [comment]
I'm not much of a Windows users, but from using it through GitHub Actions, I'm 95% sure that this is correct, things are in /Scripts not /bin.
