### ISSUE TITLE
Documentation with Regard to macOS and formatting

### ISSUE THREAD

**Issue by OldSubSailor** [pypa/packaging.python.org#798]
I apologize if I am doing this wrong. I was reading the documentation late last night and saw a reference box regarding Linux, and terminology, and think that the same needs to be pointed out for macOS and OS X. 
Even as of Big Sur, Apple included Python 2.7. Therefore if one uses commands such as:
pip install or python -m install, from the terminal, things will try to use python 2.7 and not work or generate errors.
Rather like Linux we must use 
pip3 install or python3 -m install, and Big Sur, I find that the most reliable method is to use the python3 call.

Can the documentation be modified to include a box or statement pointing out that macOS also requires the python3 format?

For example
Ensure pip, setuptools, and wheel are up to date

While pip alone is sufficient to install from pre-built binary archives, up to date copies of the setuptools and wheel projects are useful to ensure you can also install from source archives:

python3 -m pip install --upgrade pip setuptools wheel

**Comment by webknjaz** [comment]
@OldSubSailor this sounds reasonable. I think nobody will object if you send the suggested changes as a pull request so feel free to open one :)

**Comment by OldSubSailor** [comment]
I am sorry , I looked at that but got lost right away.
I will try to visit it again later
