### ISSUE TITLE
Modernize packaging tutorial

### ISSUE THREAD

**Issue by henryiii** [pypa/packaging.python.org#809]
The [packaging tutorial](https://packaging.python.org/tutorials/packaging-projects/) contains quite a lot of dated suggestions; on browsing, I see at least the following things:

* pyproject.toml is missing
* setup.py is used for metadata instead of setup.cfg
* setup.py is run manually (`python3 setup.py sdist bdist_wheel`) instead of using PyPA-build

Would you like me to update the tutorial with these suggestions?

**Comment by JulienPalard** [comment]
This page looks the most up-to-date doc of how to build today: https://setuptools.readthedocs.io/en/latest/build_meta.html, which is what I recommend, so I'd personally find it nice to have the equivalent in the packaging tutorial, yes.
