### ISSUE TITLE
ReadTheDocs is trying to build master, not main

### ISSUE THREAD

**Issue by henryiii** [pypa/packaging.python.org#819]
The website is stale, it is looking for and not finding master. This needs to be switched to main in the RtD UI.

**Comment by webknjaz** [comment]
Yep, this is true: https://readthedocs.org/projects/python-packaging-user-guide/builds/12820640/

**Comment by webknjaz** [comment]
One of @dstufft @ncoghlan @qwcode @ewdurbin @di @theacodes should be able to fix this.

**Comment by ewdurbin** [comment]
branch updated and build complete.
