### ISSUE TITLE
Typo in Python Packaging User Guide

### ISSUE THREAD

**Issue by aendie** [pypa/packaging.python.org#821]
I believe this is a simple typo on the following page:
https://packaging.python.org/tutorials/packaging-projects/

Select **setup.py (dynamic)** in the section "Configuring metadata".
It correctly shows:

![image](https://user-images.githubusercontent.com/13238632/106784977-3608e680-664d-11eb-843a-1460bb90acfc.png)

Now select **setup.cfg (static)** ...... it shows:

![image](https://user-images.githubusercontent.com/13238632/106785147-618bd100-664d-11eb-93aa-7bf92b13696e.png)

Surely you don't open **setup.py** and enter the following content.
I think one should open **setup.cfg** and enter the following content.

**Comment by webknjaz** [comment]
Good catch! Feel free to submit a PR fixing this :)

**Comment by aendie** [comment]
Hello Sviatoslav,

I click on “Found a bug” at the bottom right of the page – I don’t know how to do more unfortunately.

Could you submit the PR?

Thanks!!!!

**Comment by webknjaz** [comment]
@aendie oh, that's easy. Just go to 
https://github.com/pypa/packaging.python.org/blob/main/source/tutorials/packaging-projects.rst, click the ✏ Edit button, and it'll hit you how to make a PR once you change the text.
![IMG_20210204_010310](https://user-images.githubusercontent.com/578543/106825361-0249b300-6685-11eb-87ee-9ece5247f34a.jpg)

**Comment by aendie** [comment]
DONE  (and thanks for your help).
