### ISSUE TITLE
Promoting Sviatoslav Sydorenko as maintainer of the PUG

### ISSUE THREAD

**Issue by di** [pypa/packaging.python.org#825]
I've found @webknjaz to be doing a great job of triaging incoming PRs here and providing meaningful reviews. He's prompted me to review several PRs in a row after he's reviewed them and each time I have no additional comments.

I have no problems promoting him to maintainer of the guide. Is anyone in favor or opposed? @webknjaz, would you like to be a maintainer here?

**Comment by webknjaz** [comment]
I'd be okay with merging most of the trivial changes by myself but also many other things still need another pair of eyes (or more) :)

**Comment by pradyunsg** [comment]
I'm in favour! :)

**Comment by di** [comment]
Done!
