### ISSUE TITLE
Be bold: prefer pip over easy_install

### ISSUE THREAD

**Issue by qsqa** [pypa/packaging.python.org#830]
At [https://packaging.python.org/discussions/pip-vs-easy-install/](https://packaging.python.org/discussions/pip-vs-easy-install/), it would be helpful to note that easy_install is now deprecated.

**Comment by webknjaz** [comment]
@qsqa That's a good idea. Feel free to send a PR modifying https://github.com/pypa/packaging.python.org/blob/main/source/discussions/pip-vs-easy-install.rst.
