### ISSUE TITLE
Enable automerge in the repo settings

### ISSUE THREAD

**Issue by webknjaz** [pypa/packaging.python.org#836]
Essentially, it allows telling GH to merge a PR once all CI-like checks are green (and branch other protection restrictions are satisfied). With this feature, I can close the PR tab in my browser and let it get merged by itself, whenever the CI jobs finish.

@di this is a useful feature but I don't have access to enable it. It's just a checkbox in the repo settings.

It's called `Allow auto-merge` and should be in this section: https://github.com/pypa/packaging.python.org/settings#merge-button-settings-desc.

**Comment by pradyunsg** [comment]
I’ve enabled this and required reviews, because we probably don’t want random unreviewed PRs being merged. :)

**Comment by webknjaz** [comment]
Makes sense. OTOH it's not like anybody clicks merge w/o looking at the content :)
