### ISSUE TITLE
Step in packaging guide to create `setup.py' might cause confusion

### ISSUE THREAD

**Issue by layday** [pypa/packaging.python.org#838]
The "Creating the package files" step instructs readers to create a `setup.py`, which remains empty, leading to build failures:

* https://github.com/pypa/packaging-problems/issues/453
* https://github.com/pypa/packaging-problems/issues/454
* https://github.com/pypa/packaging-problems/issues/455

The guide later mentions that, "If you include [setup.py], you must have a call to setup() in it", but this appears to be easily overlooked.

**Comment by Nines9S** [comment]
Was scratching my head for ages wondering what I was doing wrong. Looks like I skimmed over that line too, it's very easily missed for sure. Finally got it working thanks to you!

**Comment by webknjaz** [comment]
Would turning it into an admonition help?
