### ISSUE TITLE
Code and tutorial not matching

### ISSUE THREAD

**Issue by jacoporepossi** [pypa/packaging.python.org#847]
Hi all,
I'm a bit confused because on 56d3120 you switched over to using the src/ layout but the [tutorial](https://packaging.python.org/tutorials/packaging-projects/) still shows this example:
```
packaging_tutorial
├── LICENSE
├── README.md
├── example_pkg
│   └── __init__.py
├── pyproject.toml
├── setup.cfg
├── setup.py
└── tests
```

I was just wondering which layout is preferred/suggested by pypa (and if src/layout is the optimal choise, perhaps the guide needs an update since it's confusing).

Thank you!

**Comment by di** [comment]
The `src`-based layout is preferred! I've transferred this issue to https://github.com/pypa/packaging.python.org so it can be addressed in the tutorial there.

**Comment by webknjaz** [comment]
FTR here are some notes from PyPA Mini-Summit (PyCon 2019):
https://docs.google.com/document/d/1Wz2-ECkicJgAmQDxMFivWmU2ZunKvPZ2UfQ59zDGj7g/edit#heading=h.2cgqnlxl8y3e.
There are action items at the end of this section.
