### ISSUE TITLE
On Numpy versions: can we use environment_markers?

### ISSUE THREAD

**Issue by datakid** [pypa/packaging.python.org#848]
`numpy` recently updated to version `1.20.x`, which deprecated `python 3.6`

CentOS 7.x has `python3.6` as it's latest available `python3`. 

Due to the changes that have happened to CentOS 8.x, CentOS 7.x will be kept beyond planned update schedules given it's still supported.

Can [setup.py](https://github.com/novnc/websockify/blob/24c3f75edefe49473389c5e11f4af335d49b6e75/setup.py#L32)'s `install_requires=['numpy']` utilise [environment markers](https://www.python.org/dev/peps/pep-0508/#environment-markers) per [this advice](https://stackoverflow.com/a/32643122/317217) to allow for older OSes:

```
install_requires=[
   'numpy < 1.20.0; python_version < "3.7.0" ',
   'numpy; python_version >= "3.7.0" ',
]
```
I think that's how it would work.

**Comment by di** [comment]
Yes, see https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html#platform-specific-dependencies.

**Comment by webknjaz** [comment]
I just want to add that some old setuptools versions may not support this and the compatible way of doing the same would be:
```python
extras_require = {
   ':python_version < "3.7.0"': ['numpy < 1.20.0'],
   ':python_version >= "3.7.0"': ['numpy'],
},
```
or maybe
```python
install_requires = [
   'numpy',
]
extras_require = {
   ':python_version < "3.7.0"': ['numpy < 1.20.0'],
},
```
but if you don't need to support ancient setuptools, you don't need this older syntax.
