### ISSUE TITLE
Include PEP 639 in Core metadata specifications

### ISSUE THREAD

**Issue by pyfisch** [pypa/packaging.python.org#852]
Include [PEP 639](https://www.python.org/dev/peps/pep-0639/) in [Core metadata specifications](https://packaging.python.org/specifications/core-metadata/). `License-File` is missing from the list, other changes should be included too.

**Comment by pradyunsg** [comment]
PEP 639 is a Draft, and not an accepted PEP. It's not a currently active standard.

**Comment by pradyunsg** [comment]
https://discuss.python.org/t/pep-639-improving-license-clarity-with-better-package-metadata/2154/141 is where the current discussions about it are taking place.

Closing since this isn't actionable right now, but thanks for filing this issue @pyfisch! ^>^

**Comment by pyfisch** [comment]
Thanks for pointing out, that it is still a draft.
