### ISSUE TITLE
Clarify "Packaging Python Projects" tutorial

### ISSUE THREAD

**Issue by bhrutledge** [pypa/packaging.python.org#866]
First, **thank you** for the work to update the tutorial to use `pyproject.toml`, `setup.cfg`, and `build`! Looks like that was mostly related to #809.

I've been noticing what seems like an uptick in issues on https://github.com/pypa/packaging-problems/issues/, particularly related to `python3 -m build`. That prompted me to work through the tutorial from scratch, doing my best to keep a beginner's perspective. The outcome is a bunch of thoughts on how it could be clearer, which can be viewed as [annotations to the live site](https://hyp.is/go?url=http%3A%2F%2Fpackaging.python.org%2Ftutorials%2Fpackaging-projects.html&group=__world__) (via the [Hypothesis web annotation tool](https://web.hypothes.is/)).

Besides a bunch of small copy-edits, there are some bigger questions about the content, e.g.

- How much detail is necessary for the intended audience?
- When/how should we explain "editable installs"?
- Should this whole thing be done in a virtual environment?

Before diving into submitting a PR for any/all of these things, I'd love some feedback on my feedback. 😉

**Comment by di** [comment]
> I think that tutorials shouldn't be too low-level. They need to show one way, without any branching

+1 to this.

@bhrutledge I'm certain your feedback is valuable, please feel free to go ahead and create a PR so we can review directly.

**Comment by bhrutledge** [comment]
First batch submitted. I'll wait until those are merged before working on further changes.

**Comment by henryiii** [comment]
FYI, some of the extra issues have been related to a few bugs in build, several of which are being fixed in the version about to be rolled out. I think the issues will slow down a little after that.

So far the changes look great. :)

I'm wondering if we could update to using pipx in the future? Using `pipx run build`, `pipx run twine`, etc. would help with the lack of virtual environments, and would remove some of the "set the next part up by installing this" steps.

**Comment by bhrutledge** [comment]
> I'm wondering if we could update to using pipx in the future? Using `pipx run build`, `pipx run twine`, etc. would help with the lack of virtual environments, and would remove some of the "set the next part up by installing this" steps.

While I love pipx, I'm wary of introducing an additional tool, especially one that's not a PyPA project. I'd rather encourage the use of a virtual environment, which folks should already be familiar with from the [Installing Packages tutorial](https://packaging.python.org/tutorials/installing-packages/).

**Comment by bhrutledge** [comment]
> So far the changes look great. :)

Thanks! My next step is to simplify/clarify the language around `setup.py` and editable installs.

**Comment by pradyunsg** [comment]
> especially one that's not a PyPA project.

That'll change in a few days: https://mail.python.org/archives/list/pypa-committers@python.org/thread/JMT66ZZHAGY3OYU26ANKOOUXV2Q2C7O6/

**Comment by pradyunsg** [comment]
I do think it's still worthwhile to keep recommending virtual environments for now though. pipx can probably be a separate recommendation.

**Comment by webknjaz** [comment]
I'd rather not recommend pipx because we'd have to explain how to provision it on different OSs which belongs in other places. Also, I don't think we favor pipx over virtualenv.
