### ISSUE TITLE
URLs with trailing slashes aren't working

### ISSUE THREAD

**Issue by bhrutledge** [pypa/packaging.python.org#876]
A recent build of the Twine docs [failed with this error](https://github.com/pypa/twine/runs/2319520105?check_suite_focus=true#step:5:222):

```
/home/runner/work/twine/twine/docs/changelog.rst.rst:5:broken link: https://packaging.python.org/guides/distributing-packages-using-setuptools/#pre-release-versioning (404 Client Error: Not Found for url: https://packaging.python.org/guides/distributing-packages-using-setuptools/)
```

At the moment, that URL shows the RTD "This page does not exist yet" error.

The same thing is happening on internal links in the docs, such as "An Overview of Packaging for Python" in the table of contents. The `href` is referencing `overview.html`, but clicking on the link results in a 301 redirect to `/overview/`, which results in a 404.

**Comment by noahkw** [comment]
For me, all of the links that are not section overviews are broken, i.e.: 

https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/

https://packaging.python.org/discussions/install-requires-vs-requirements/

This is with or without trailing slashes.

**Comment by webknjaz** [comment]
Thanks for the report! #877 should fix this. Also ref https://github.com/pyca/cryptography/issues/5863#issuecomment-792343136.

**Comment by webknjaz** [comment]
Upstream report: https://github.com/readthedocs/readthedocs.org/issues/8092
