### ISSUE TITLE
packaging.python.org appears broken - Maze found errors

### ISSUE THREAD

**Issue by sergei-maertens** [pypa/packaging.python.org#878]
Hi, we noticed that the documentation website is having issues because of a failing Sphinx build with enabled link checker.

We link to https://packaging.python.org/tutorials/installing-packages.html, which is currently throwing a "Maze found" error. This appears to not be intentional, as the tutorials index page (https://packaging.python.org/tutorials/) still links to this page.

**Comment by sergei-maertens** [comment]
Upon closer look, this seems related to #876 as well

**Comment by webknjaz** [comment]
> Upon closer look, this seems related to #876 as well

Yes, thanks for the report. Fixed by #877.

**Comment by sergei-maertens** [comment]
thanks for the quick resolution!
