### ISSUE TITLE
Add examples to metadata in pyproject.toml page

### ISSUE THREAD

**Issue by FFY00** [pypa/packaging.python.org#895]
PEP 621 defines a standard format for package metadata in `pyproject.toml`. I expect several backends to implement it, but not all to produce high quality documentation on how to use it, specially small domain-specific backends. It would be great to have a tutorial/description of the fields packaging.python.org that backends could point users to. Right now, the best option is to point to the PEP itself.

**Comment by henryiii** [comment]
Would it be best to add right after or simultaneously with either setuptools or the first implementing backend? (cibuildwheel is sort-of first, but only for requires-python ;) ) It's going to be rather confusing if there's a guide for something but it can't be used yet.

**Comment by FFY00** [comment]
I was envisioning this more like a separate page backends could point to. The setuptools documentation could show an example, as it is fairly straightforward, and have a link for the fill documentation for more details.

**Comment by domdfcoding** [comment]
I semi-rewrote PEP 621 as part of the docs for whey (see https://whey.readthedocs.io/en/latest/configuration.html), removing the parts aimed at backend authors and adding examples for each field.

Is that the sort of thing you were thinking of?

**Comment by pradyunsg** [comment]
Yea, that looks about right.

**Comment by FFY00** [comment]
Yes, exactly. That documentation will be the same for everyone, so better avoid duplicated efforts.

**Comment by pradyunsg** [comment]
We have this mostly, with https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#dependencies-optional-dependencies. This still needs examples though, so a PR for that would be welcome.
