### ISSUE TITLE
Wrong package name in guide's example

### ISSUE THREAD

**Issue by dtsap** [pypa/packaging.python.org#899]
There is a mistake on an example of installing packages tutorial (https://packaging.python.org/tutorials/installing-packages/) under Creating Virtual Environments section, that is about how to use the virtualenv package, in which the venv package is wrongly used (python3 -m venv <DIR>) instead of virtualenv.

**Comment by webknjaz** [comment]
Do you want to send a pull request? The source is here https://github.com/pypa/packaging.python.org/blob/main/source/tutorials/installing-packages.rst

**Comment by dtsap** [comment]
sure

**Comment by webknjaz** [comment]
Thanks!
