### ISSUE TITLE
packaging exercise: build fails because ensurepip is not available

### ISSUE THREAD

**Issue by bryandenniskeith** [pypa/packaging.python.org#905]
I went all the way through the packaging exercise with a successful `build`.  I used a virtual environmental (for the first time) to successfully install my new package.  The process failed on `import example_pkg`  I made some changes to my `setup.cfg`, and when I went to `build` again, `build` failed like this:

```
/packaging_tutorial$ python3 -m build
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt-get install python3-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/tmp/build-env-x4d5e48m/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']

```
However, using `venv` works:

```
$ mkdir venv_test
$ python3 -m venv venv_test
$ source venv_test/bin/activate
(venv_test) $ 

```
**if** I am in a different directory.  If I am in the `packaging_tutorial` directory, `venv` fails:

```
/packaging_tutorial$ mkdir venv_test
/packaging_tutorial$ python3 -m venv venv_test/
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt-get install python3-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/home/bryan/fun/routing/packaging_tutorial/venv_test/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']

```
What's going on here?  I imagine this issue is not directly related to the packaging exercise.  However, I am not familiar with `venv`.  If there is a better place to ask this question (also, I can't see how to tag this as a question), please let me know.

Bryan

**Comment by webknjaz** [comment]
I believe you may be hitting https://gist.github.com/tiran/2dec9e03c6f901814f6d1e8dad09528e. Also, most of the Linux distros, when repackaging CPython (or third party Python packages), decouple its parts into many separate packages (even though they are all originally bundled together in the upstream project). And so to get them, you must explicitly install those by running the commands prompted in those error messages.

**Comment by bryandenniskeith** [comment]
Well, after a little more testing...  If I have this:

```
[options]
package_dir =
    = example_pkg
packages = find:
python_requires = >=3.6

```
in my `setup.cfg`, then `python3 -m build` runs fine.

If I add this line (because I'm trying to fix the `No module name example_pkg` error that I get after installing my package in a virtual environment):

`packages = example_pkg`

then `python3 -m build` fails as I previously describe.  @webknjaz is this a symptom of the issue that you pointed out or is there something else going on here?

BTW, I am using ubuntu:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

```

**Comment by doko42** [comment]
sorry, it's unclear to me what exactly you are doing, and where you started from.  Maybe you could describe the steps taken from the start?

Also how accurate are the guides? Still seeing references to easy_install, and the installing-using-linux-tools guide has seen a last update in 2015 ...

**Comment by bryandenniskeith** [comment]
@doko42 I was following the steps in this tutorial: https://packaging.python.org/tutorials/packaging-projects/

and made it all the way through the end only to have this error at the end after installing my new package in a virtual environment: `No module named 'example_pkg'`

The problem was that I was trying to put my project in root rather than in src as the tutorial suggests so I had my `setup.cfg` like this:
```
[options]
package_dir =
    = example_pkg
packages = find:
python_requires = >=3.6
```
Not sure what to do next I tried my setup.cfg like this:
```
[options]
package_dir =
    = example_pkg
packages = find:
python_requires = >=3.6
packages = example_pkg
```
Adding that single line caused `python3 -m build` to give me this error:
```
/packaging_tutorial$ python3 -m build
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt-get install python3-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/tmp/build-env-x4d5e48m/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']
```
which seems rather confusing.

I'm not really concerned about this anymore as now I have fixed the problems in my `setup.cfg` (by putting my package in src as   @webknjaz suggested) and am able to `import example_pkg` successfully.  However, if this is an issue that you want to dig into further, I'm happy to try and help.

**Comment by doko42** [comment]
did you install python3-venv as the message suggested?

**Comment by bryandenniskeith** [comment]
Yes.  I also tested that I could create virtual environments using `venv` in other directories.  That worked but failed in my `packaging_tutorial` directory.  Before making changes to the `setup.cfg` I tried uninstalling and reinstalling python3-venv and also specifically python3.8-venv, but none of that made a difference.  Changing `setup.cfg` as I described made the problem go away.

**Comment by webknjaz** [comment]
> ```
> [options]
> package_dir =
>     = example_pkg
> packages = find:
> ...
> packages = example_pkg
> ```

With this you tell setuptools that your target package is located at `example_pkg/example_pkg/`.

As I said in another thread, you want to remove `package_dir` instead. Although, the general recommendation is to use src-layout because the natural layout makes testing unobvious.

But this mistake is separate from missing packages on your system. I personally recommend avoiding system Python (especially on Debian/Ubuntu) for many reasons and I use pyenv for having multiple Pythons in my userspace. But this is a more advanced topic so I suggest you explore it separately.

**Comment by bryandenniskeith** [comment]
Thank you.  Yes, now I have it working with the src layout.

**Comment by webknjaz** [comment]
Can this issue be closed now?

**Comment by bryandenniskeith** [comment]
Yes.
