### ISSUE TITLE
Change links to IRC

### ISSUE THREAD

**Issue by bhrutledge** [pypa/packaging.python.org#915]
As noted in [IRC webchat is down. What does this mean for PyPA? - Packaging - Discussions on Python.org](https://discuss.python.org/t/irc-webchat-is-down-what-does-this-mean-for-pypa/9324), the PyPA IRC has moved from Freenode to Libera.Chat. It looks like the only links are in the [key projects listing](https://github.com/pypa/packaging.python.org/blob/main/source/key_projects.rst). The new links should be, for example, https://web.libera.chat/#pypa.

**Comment by webknjaz** [comment]
There's also links in the issue selectors / forms of various repos. We'd need to grep everything under the org to find all the mentions.

**Comment by bhrutledge** [comment]
I was thinking those would be handled by the various projects, so that the scope of this issue was just for this repo.

**Comment by webknjaz** [comment]
Yes, sure. Just wanted to mention this explicitly.
