### ISSUE TITLE
Promoting Brian Rutledge as maintainer of the PUG

### ISSUE THREAD

**Issue by webknjaz** [pypa/packaging.python.org#926]
@bhrutledge has been exceptionally active in this repository in recent months and sent some contributions a year ago too.

I propose to promote Brian to a maintainer because I believe he can be a huge help in moving the PUG forward. His past PRs have always been well-thought and he is very collaborative when something needs discussing or polishing.

He's also mentioned that he is interested in stepping up @ https://discuss.python.org/t/whats-the-best-way-to-help-with-packaging-python-org/9387/2?u=webknjaz.

cc @pypa/packaging-user-guide-editors

**Comment by bhrutledge** [comment]
Thanks for the vote of confidence, @webknjaz.  😊

**Comment by theacodes** [comment]
👍

**Comment by brainwane** [comment]
Yeah, this sounds good to me!

**Comment by pradyunsg** [comment]
Added Brian to the relevant GitHub team!
