### ISSUE TITLE
installing-using-pip: Update command output

### ISSUE THREAD

**Issue by bhrutledge** [pypa/packaging.python.org#931]
As noted in in https://github.com/pypa/packaging.python.org/pull/928#discussion_r659366032, there are few places in that document where the command and its output are shown in a single `code-block`, but with no distinction between them, which might lead folks to thinking that `pip 9.0.1 ...` is a command to execute. If the output of a command is valuable, I recommend putting it into a separate `.. code-block:: text`.

Also, the output from the `pip --version` is quite old. Let's take this opportunity to update it.

**Comment by webknjaz** [comment]
Honestly, I think it's a wrong solution — it's natural to see the console output for as long as the prompt is present and the correct lexer for sessions is set.
