### ISSUE TITLE
The windows examples use "bash" and backslashes

### ISSUE THREAD

**Issue by henryiii** [pypa/packaging.python.org#934]
This creates weird highlighting especially with backslashes in paths. I think we can use the `.. code-block:: bat` lexer instead.

_Originally posted by @henryiii in https://github.com/pypa/packaging.python.org/pull/928#issuecomment-869787000_

**Comment by bhrutledge** [comment]
Or `.. code-block:: text`, which is what's currently used for other Windows output in `installing-using-pip-and-virtual-environments.rst`.

See also #931.
