### ISSUE TITLE
Normalize command lines in code blocks

### ISSUE THREAD

**Issue by bhrutledge** [pypa/packaging.python.org#947]
In most places where there's a command line, it's shown without a prompt, e.g.

```rst
.. code-block:: bash

    python3 --version
```

However, there are some places where it's preceded by a prompt character:

```rst
::

  $ pipx run cowsay moooo
```

I think we should remove the prompt characters entirely, and standardize on `code-block:: bash` (plus `code-block:: bat` for Windows if the command is different). For places where that's not practical (i.e. where including the prompt character and/or command output improves readability), I think we should use `code-block:: console` (plus `code-block:: doscon` for Windows if the command is different).

I think this is a list of all of the occurrences of a prompt character (which notably doesn't include any use of `>` for Windows):

```console
% rg '^\s*(\$ |> )'
source/guides/installing-stand-alone-command-line-tools.rst
47:  $ pipx install PACKAGE
48:  $ ENTRYPOINT_OF_PACKAGE [ARGS]
54:  $ pipx install cowsay
59:  $ cowsay moo
74:  $ pipx list
94:  $ pipx upgrade PACKAGE
95:  $ pipx uninstall PACKAGE
118:  $ pipx run PACKAGE [ARGS]
124:  $ pipx run cowsay moooo
130:  $ pipx --help

source/guides/analyzing-pypi-package-downloads.rst
283:    $ pypinfo requests

source/guides/index-mirrors-and-caches.rst
40:    $ python -m pip wheel --wheel-dir=/tmp/wheelhouse SomeProject
41:    $ python -m pip install --no-index --find-links=/tmp/wheelhouse SomeProject

source/guides/using-testpypi.rst
31:    $ twine upload --repository testpypi dist/*
```

**Comment by meowmeowmeowcat** [comment]
@bhrutledge Do we need to keep using the prompt in this command?
```shell
$ ENTRYPOINT_OF_PACKAGE [ARGS]
```
I think folks won't know it is a command if we remove the prompt.

**Comment by bhrutledge** [comment]
@meowmeowmeowcat Thanks for asking. To clarify, I don't think we want to remove _all_ prompts (at the moment):

> For places where that's not practical (i.e. where including the prompt character and/or command output improves readability), I think we should use `code-block:: console` (plus `code-block:: doscon` for Windows if the command is different).

So, to answer your question, yes. That said, I might follow-up with a separate PR that replaces `ENTRYPOINT_OF_PACKAGE` with a concrete example.

**Comment by meowmeowmeowcat** [comment]
@bhrutledge Thanks for clarification!
