### ISSUE TITLE
manifest.in document is poor

### ISSUE THREAD

**Issue by shi-yan** [pypa/packaging.python.org#989]
this is a poor document regarding manifest.in usage.

https://packaging.python.org/guides/using-manifest-in/

for example it doesn't contain any example for using recursive-include

```
recursive-include folder
recursive-include parent/folder
```
don't work at all.

it has to be 

```
recursive-include folder *.html
```

**Comment by webknjaz** [comment]
Feel free to send a PR.

**Comment by jeanas** [comment]
Moved to https://github.com/pypa/setuptools/issues/4158.
