### ISSUE TITLE
objects.inv vanished from docs (404 error)

### ISSUE THREAD

**Issue by ssbarnea** [pypa/packaging.python.org#995]
Apparently an URL that worked previously now returns 404:
```
loading intersphinx inventory from https://packaging.python.org/en/latest/objects.inv...
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://packaging.python.org/en/latest/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 404 Client Error: Not Found for url: https://packaging.python.org/en/latest/objects.inv
```

If the location of `objects.inv` has changed, can you please provide its new location? I searched for related bugs but did not find any.

**Comment by meowmeowmeowcat** [comment]
@ssbarnea The location of `objects.inv` should be https://packaging.python.org/objects.inv.

**Comment by ssbarnea** [comment]
Thanks!

**Comment by ssbarnea** [comment]
While I was able to address the moved `objects.inv` I now [faces another error](https://github.com/ansible-community/ansible-compat/runs/3802866563?check_suite_focus=true#step:7:35), which is caused by a warning from sphinx:
```
/Users/ssbarnea/c/a/ansible-compat/src/ansible_compat/runtime.py:docstring of ansible_compat.runtime.Runtime.version:: WARNING: py:class reference target not found: packaging.version.Version
```

Considering that I fixed the objects.inv location, I wonder if the new file no longer have the docs for version, causing this. As objects.inv is not really human friendly I am not sure how to address that.

I used https://github.com/bskinn/sphobjinv and run:
```
sphobjinv suggest objects.inv Version
 
:std:term:`Version Specifier`
:std:label:`choosing a versioning scheme`
:std:label:`core-metadata-version`
:std:doc:`guides/dropping-older-python-versions`
:std:doc:`guides/multi-version-installs`
:std:doc:`guides/single-sourcing-package-version`
:std:doc:`guides/supporting-multiple-python-versions`
:std:label:`multi-version installs`
:std:label:`single sourcing the version`
:std:doc:`specifications/version-specifiers`
:std:label:`supporting multiple python versions`
:std:label:`version-specifiers`
```

That makes me believe that there is no Version inside the new file.

**Comment by webknjaz** [comment]
> ```
> /Users/ssbarnea/c/a/ansible-compat/src/ansible_compat/runtime.py:docstring of ansible_compat.runtime.Runtime.version:: WARNING: py:class reference target not found: packaging.version.Version
> ```

This is a reference to a different project. The one you're looking for is https://packaging.pypa.io/en/latest/ / https://github.com/pypa/packaging.

P.S. I have a static site that presents many intersphinx references for different sphinx docs that you may use to look up what's available right from your browser https://webknjaz.github.io/intersphinx-untangled/.
